export const ICONS = {
  123: "123", //eb8d
  360: "360", //e577
  "10K": "10k", //e951
  "10MP": "10mp", //e952
  "11MP": "11mp", //e953
  "12MP": "12mp", //e954
  "13MP": "13mp", //e955
  "14MP": "14mp", //e956
  "15MP": "15mp", //e957
  "16MP": "16mp", //e958
  "17MP": "17mp", //e959
  "18_UP_RATING": "18_up_rating", //f8fd
  "18MP": "18mp", //e95a
  "19MP": "19mp", //e95b
  "1K": "1k", //e95c
  "1K_PLUS": "1k_plus", //e95d
  "1X_MOBILEDATA": "1x_mobiledata", //efcd
  "20MP": "20mp", //e95e
  "21MP": "21mp", //e95f
  "22MP": "22mp", //e960
  "23MP": "23mp", //e961
  "24MP": "24mp", //e962
  "2K": "2k", //e963
  "2K_PLUS": "2k_plus", //e964
  "2MP": "2mp", //e965
  "30FPS": "30fps", //efce
  "30FPS_SELECT": "30fps_select", //efcf
  "3D_ROTATION": "3d_rotation", //e84d
  "3G_MOBILEDATA": "3g_mobiledata", //efd0
  "3K": "3k", //e966
  "3K_PLUS": "3k_plus", //e967
  "3MP": "3mp", //e968
  "3P": "3p", //efd1
  "4G_MOBILEDATA": "4g_mobiledata", //efd2
  "4G_PLUS_MOBILEDATA": "4g_plus_mobiledata", //efd3
  "4K": "4k", //e072
  "4K_PLUS": "4k_plus", //e969
  "4MP": "4mp", //e96a
  "5G": "5g", //ef38
  "5K": "5k", //e96b
  "5K_PLUS": "5k_plus", //e96c
  "5MP": "5mp", //e96d
  "60FPS": "60fps", //efd4
  "60FPS_SELECT": "60fps_select", //efd5
  "6_FT_APART": "6_ft_apart", //f21e
  "6K": "6k", //e96e
  "6K_PLUS": "6k_plus", //e96f
  "6MP": "6mp", //e970
  "7K": "7k", //e971
  "7K_PLUS": "7k_plus", //e972
  "7MP": "7mp", //e973
  "8K": "8k", //e974
  "8K_PLUS": "8k_plus", //e975
  "8MP": "8mp", //e976
  "9K": "9k", //e977
  "9K_PLUS": "9k_plus", //e978
  "9MP": "9mp", //e979
  ABC: "abc", //eb94
  AC_UNIT: "ac_unit", //eb3b
  ACCESS_ALARM: "access_alarm", //e190
  ACCESS_ALARMS: "access_alarms", //e191
  ACCESS_TIME: "access_time", //e192
  ACCESS_TIME_FILLED: "access_time_filled", //efd6
  ACCESSIBILITY: "accessibility", //e84e
  ACCESSIBILITY_NEW: "accessibility_new", //e92c
  ACCESSIBLE: "accessible", //e914
  ACCESSIBLE_FORWARD: "accessible_forward", //e934
  ACCOUNT_BALANCE: "account_balance", //e84f
  ACCOUNT_BALANCE_WALLET: "account_balance_wallet", //e850
  ACCOUNT_BOX: "account_box", //e851
  ACCOUNT_CIRCLE: "account_circle", //e853
  ACCOUNT_TREE: "account_tree", //e97a
  AD_UNITS: "ad_units", //ef39
  ADB: "adb", //e60e
  ADD: "add", //e145
  ADD_A_PHOTO: "add_a_photo", //e439
  ADD_ALARM: "add_alarm", //e193
  ADD_ALERT: "add_alert", //e003
  ADD_BOX: "add_box", //e146
  ADD_BUSINESS: "add_business", //e729
  ADD_CARD: "add_card", //eb86
  ADD_CHART: "add_chart", //e97b
  ADD_CIRCLE: "add_circle", //e147
  ADD_CIRCLE_OUTLINE: "add_circle_outline", //e148
  ADD_COMMENT: "add_comment", //e266
  ADD_HOME: "add_home", //f8eb
  ADD_HOME_WORK: "add_home_work", //f8ed
  ADD_IC_CALL: "add_ic_call", //e97c
  ADD_LINK: "add_link", //e178
  ADD_LOCATION: "add_location", //e567
  ADD_LOCATION_ALT: "add_location_alt", //ef3a
  ADD_MODERATOR: "add_moderator", //e97d
  ADD_PHOTO_ALTERNATE: "add_photo_alternate", //e43e
  ADD_REACTION: "add_reaction", //e1d3
  ADD_ROAD: "add_road", //ef3b
  ADD_SHOPPING_CART: "add_shopping_cart", //e854
  ADD_TASK: "add_task", //f23a
  ADD_TO_DRIVE: "add_to_drive", //e65c
  ADD_TO_HOME_SCREEN: "add_to_home_screen", //e1fe
  ADD_TO_PHOTOS: "add_to_photos", //e39d
  ADD_TO_QUEUE: "add_to_queue", //e05c
  ADDCHART: "addchart", //ef3c
  ADF_SCANNER: "adf_scanner", //eada
  ADJUST: "adjust", //e39e
  ADMIN_PANEL_SETTINGS: "admin_panel_settings", //ef3d
  ADOBE: "adobe", //ea96
  ADS_CLICK: "ads_click", //e762
  AGRICULTURE: "agriculture", //ea79
  AIR: "air", //efd8
  AIRLINE_SEAT_FLAT: "airline_seat_flat", //e630
  AIRLINE_SEAT_FLAT_ANGLED: "airline_seat_flat_angled", //e631
  AIRLINE_SEAT_INDIVIDUAL_SUITE: "airline_seat_individual_suite", //e632
  AIRLINE_SEAT_LEGROOM_EXTRA: "airline_seat_legroom_extra", //e633
  AIRLINE_SEAT_LEGROOM_NORMAL: "airline_seat_legroom_normal", //e634
  AIRLINE_SEAT_LEGROOM_REDUCED: "airline_seat_legroom_reduced", //e635
  AIRLINE_SEAT_RECLINE_EXTRA: "airline_seat_recline_extra", //e636
  AIRLINE_SEAT_RECLINE_NORMAL: "airline_seat_recline_normal", //e637
  AIRLINE_STOPS: "airline_stops", //e7d0
  AIRLINES: "airlines", //e7ca
  AIRPLANE_TICKET: "airplane_ticket", //efd9
  AIRPLANEMODE_ACTIVE: "airplanemode_active", //e195
  AIRPLANEMODE_INACTIVE: "airplanemode_inactive", //e194
  AIRPLANEMODE_OFF: "airplanemode_off", //e194
  AIRPLANEMODE_ON: "airplanemode_on", //e195
  AIRPLAY: "airplay", //e055
  AIRPORT_SHUTTLE: "airport_shuttle", //eb3c
  ALARM: "alarm", //e855
  ALARM_ADD: "alarm_add", //e856
  ALARM_OFF: "alarm_off", //e857
  ALARM_ON: "alarm_on", //e858
  ALBUM: "album", //e019
  ALIGN_HORIZONTAL_CENTER: "align_horizontal_center", //e00f
  ALIGN_HORIZONTAL_LEFT: "align_horizontal_left", //e00d
  ALIGN_HORIZONTAL_RIGHT: "align_horizontal_right", //e010
  ALIGN_VERTICAL_BOTTOM: "align_vertical_bottom", //e015
  ALIGN_VERTICAL_CENTER: "align_vertical_center", //e011
  ALIGN_VERTICAL_TOP: "align_vertical_top", //e00c
  ALL_INBOX: "all_inbox", //e97f
  ALL_INCLUSIVE: "all_inclusive", //eb3d
  ALL_OUT: "all_out", //e90b
  ALT_ROUTE: "alt_route", //f184
  ALTERNATE_EMAIL: "alternate_email", //e0e6
  AMP_STORIES: "amp_stories", //ea13
  ANALYTICS: "analytics", //ef3e
  ANCHOR: "anchor", //f1cd
  ANDROID: "android", //e859
  ANIMATION: "animation", //e71c
  ANNOUNCEMENT: "announcement", //e85a
  AOD: "aod", //efda
  APARTMENT: "apartment", //ea40
  API: "api", //f1b7
  APP_BLOCKING: "app_blocking", //ef3f
  APP_REGISTRATION: "app_registration", //ef40
  APP_SETTINGS_ALT: "app_settings_alt", //ef41
  APP_SHORTCUT: "app_shortcut", //eae4
  APPLE: "apple", //ea80
  APPROVAL: "approval", //e982
  APPS: "apps", //e5c3
  APPS_OUTAGE: "apps_outage", //e7cc
  ARCHITECTURE: "architecture", //ea3b
  ARCHIVE: "archive", //e149
  AREA_CHART: "area_chart", //e770
  ARROW_BACK: "arrow_back", //e5c4
  ARROW_BACK_IOS: "arrow_back_ios", //e5e0
  ARROW_BACK_IOS_NEW: "arrow_back_ios_new", //e2ea
  ARROW_CIRCLE_DOWN: "arrow_circle_down", //f181
  ARROW_CIRCLE_LEFT: "arrow_circle_left", //eaa7
  ARROW_CIRCLE_RIGHT: "arrow_circle_right", //eaaa
  ARROW_CIRCLE_UP: "arrow_circle_up", //f182
  ARROW_DOWNWARD: "arrow_downward", //e5db
  ARROW_DROP_DOWN: "arrow_drop_down", //e5c5
  ARROW_DROP_DOWN_CIRCLE: "arrow_drop_down_circle", //e5c6
  ARROW_DROP_UP: "arrow_drop_up", //e5c7
  ARROW_FORWARD: "arrow_forward", //e5c8
  ARROW_FORWARD_IOS: "arrow_forward_ios", //e5e1
  ARROW_LEFT: "arrow_left", //e5de
  ARROW_OUTWARD: "arrow_outward", //f8ce
  ARROW_RIGHT: "arrow_right", //e5df
  ARROW_RIGHT_ALT: "arrow_right_alt", //e941
  ARROW_UPWARD: "arrow_upward", //e5d8
  ART_TRACK: "art_track", //e060
  ARTICLE: "article", //ef42
  ASPECT_RATIO: "aspect_ratio", //e85b
  ASSESSMENT: "assessment", //e85c
  ASSIGNMENT: "assignment", //e85d
  ASSIGNMENT_IND: "assignment_ind", //e85e
  ASSIGNMENT_LATE: "assignment_late", //e85f
  ASSIGNMENT_RETURN: "assignment_return", //e860
  ASSIGNMENT_RETURNED: "assignment_returned", //e861
  ASSIGNMENT_TURNED_IN: "assignment_turned_in", //e862
  ASSIST_WALKER: "assist_walker", //f8d5
  ASSISTANT: "assistant", //e39f
  ASSISTANT_DIRECTION: "assistant_direction", //e988
  ASSISTANT_PHOTO: "assistant_photo", //e3a0
  ASSURED_WORKLOAD: "assured_workload", //eb6f
  ATM: "atm", //e573
  ATTACH_EMAIL: "attach_email", //ea5e
  ATTACH_FILE: "attach_file", //e226
  ATTACH_MONEY: "attach_money", //e227
  ATTACHMENT: "attachment", //e2bc
  ATTRACTIONS: "attractions", //ea52
  ATTRIBUTION: "attribution", //efdb
  AUDIO_FILE: "audio_file", //eb82
  AUDIOTRACK: "audiotrack", //e3a1
  AUTO_AWESOME: "auto_awesome", //e65f
  AUTO_AWESOME_MOSAIC: "auto_awesome_mosaic", //e660
  AUTO_AWESOME_MOTION: "auto_awesome_motion", //e661
  AUTO_DELETE: "auto_delete", //ea4c
  AUTO_FIX_HIGH: "auto_fix_high", //e663
  AUTO_FIX_NORMAL: "auto_fix_normal", //e664
  AUTO_FIX_OFF: "auto_fix_off", //e665
  AUTO_GRAPH: "auto_graph", //e4fb
  AUTO_MODE: "auto_mode", //ec20
  AUTO_STORIES: "auto_stories", //e666
  AUTOFPS_SELECT: "autofps_select", //efdc
  AUTORENEW: "autorenew", //e863
  AV_TIMER: "av_timer", //e01b
  BABY_CHANGING_STATION: "baby_changing_station", //f19b
  BACK_HAND: "back_hand", //e764
  BACKPACK: "backpack", //f19c
  BACKSPACE: "backspace", //e14a
  BACKUP: "backup", //e864
  BACKUP_TABLE: "backup_table", //ef43
  BADGE: "badge", //ea67
  BAKERY_DINING: "bakery_dining", //ea53
  BALANCE: "balance", //eaf6
  BALCONY: "balcony", //e58f
  BALLOT: "ballot", //e172
  BAR_CHART: "bar_chart", //e26b
  BATCH_PREDICTION: "batch_prediction", //f0f5
  BATHROOM: "bathroom", //efdd
  BATHTUB: "bathtub", //ea41
  BATTERY_0_BAR: "battery_0_bar", //ebdc
  BATTERY_1_BAR: "battery_1_bar", //ebd9
  BATTERY_2_BAR: "battery_2_bar", //ebe0
  BATTERY_3_BAR: "battery_3_bar", //ebdd
  BATTERY_4_BAR: "battery_4_bar", //ebe2
  BATTERY_5_BAR: "battery_5_bar", //ebd4
  BATTERY_6_BAR: "battery_6_bar", //ebd2
  BATTERY_ALERT: "battery_alert", //e19c
  BATTERY_CHARGING_FULL: "battery_charging_full", //e1a3
  BATTERY_FULL: "battery_full", //e1a4
  BATTERY_SAVER: "battery_saver", //efde
  BATTERY_STD: "battery_std", //e1a5
  BATTERY_UNKNOWN: "battery_unknown", //e1a6
  BEACH_ACCESS: "beach_access", //eb3e
  BED: "bed", //efdf
  BEDROOM_BABY: "bedroom_baby", //efe0
  BEDROOM_CHILD: "bedroom_child", //efe1
  BEDROOM_PARENT: "bedroom_parent", //efe2
  BEDTIME: "bedtime", //ef44
  BEDTIME_OFF: "bedtime_off", //eb76
  BEENHERE: "beenhere", //e52d
  BENTO: "bento", //f1f4
  BIKE_SCOOTER: "bike_scooter", //ef45
  BIOTECH: "biotech", //ea3a
  BLENDER: "blender", //efe3
  BLIND: "blind", //f8d6
  BLINDS: "blinds", //e286
  BLINDS_CLOSED: "blinds_closed", //ec1f
  BLOCK: "block", //e14b
  BLOODTYPE: "bloodtype", //efe4
  BLUETOOTH: "bluetooth", //e1a7
  BLUETOOTH_AUDIO: "bluetooth_audio", //e60f
  BLUETOOTH_CONNECTED: "bluetooth_connected", //e1a8
  BLUETOOTH_DISABLED: "bluetooth_disabled", //e1a9
  BLUETOOTH_DRIVE: "bluetooth_drive", //efe5
  BLUETOOTH_SEARCHING: "bluetooth_searching", //e1aa
  BLUR_CIRCULAR: "blur_circular", //e3a2
  BLUR_LINEAR: "blur_linear", //e3a3
  BLUR_OFF: "blur_off", //e3a4
  BLUR_ON: "blur_on", //e3a5
  BOLT: "bolt", //ea0b
  BOOK: "book", //e865
  BOOK_ONLINE: "book_online", //f217
  BOOKMARK: "bookmark", //e866
  BOOKMARK_ADD: "bookmark_add", //e598
  BOOKMARK_ADDED: "bookmark_added", //e599
  BOOKMARK_BORDER: "bookmark_border", //e867
  BOOKMARK_OUTLINE: "bookmark_outline", //e867
  BOOKMARK_REMOVE: "bookmark_remove", //e59a
  BOOKMARKS: "bookmarks", //e98b
  BORDER_ALL: "border_all", //e228
  BORDER_BOTTOM: "border_bottom", //e229
  BORDER_CLEAR: "border_clear", //e22a
  BORDER_COLOR: "border_color", //e22b
  BORDER_HORIZONTAL: "border_horizontal", //e22c
  BORDER_INNER: "border_inner", //e22d
  BORDER_LEFT: "border_left", //e22e
  BORDER_OUTER: "border_outer", //e22f
  BORDER_RIGHT: "border_right", //e230
  BORDER_STYLE: "border_style", //e231
  BORDER_TOP: "border_top", //e232
  BORDER_VERTICAL: "border_vertical", //e233
  BOY: "boy", //eb67
  BRANDING_WATERMARK: "branding_watermark", //e06b
  BREAKFAST_DINING: "breakfast_dining", //ea54
  BRIGHTNESS_1: "brightness_1", //e3a6
  BRIGHTNESS_2: "brightness_2", //e3a7
  BRIGHTNESS_3: "brightness_3", //e3a8
  BRIGHTNESS_4: "brightness_4", //e3a9
  BRIGHTNESS_5: "brightness_5", //e3aa
  BRIGHTNESS_6: "brightness_6", //e3ab
  BRIGHTNESS_7: "brightness_7", //e3ac
  BRIGHTNESS_AUTO: "brightness_auto", //e1ab
  BRIGHTNESS_HIGH: "brightness_high", //e1ac
  BRIGHTNESS_LOW: "brightness_low", //e1ad
  BRIGHTNESS_MEDIUM: "brightness_medium", //e1ae
  BROADCAST_ON_HOME: "broadcast_on_home", //f8f8
  BROADCAST_ON_PERSONAL: "broadcast_on_personal", //f8f9
  BROKEN_IMAGE: "broken_image", //e3ad
  BROWSE_GALLERY: "browse_gallery", //ebd1
  BROWSER_NOT_SUPPORTED: "browser_not_supported", //ef47
  BROWSER_UPDATED: "browser_updated", //e7cf
  BRUNCH_DINING: "brunch_dining", //ea73
  BRUSH: "brush", //e3ae
  BUBBLE_CHART: "bubble_chart", //e6dd
  BUG_REPORT: "bug_report", //e868
  BUILD: "build", //e869
  BUILD_CIRCLE: "build_circle", //ef48
  BUNGALOW: "bungalow", //e591
  BURST_MODE: "burst_mode", //e43c
  BUS_ALERT: "bus_alert", //e98f
  BUSINESS: "business", //e0af
  BUSINESS_CENTER: "business_center", //eb3f
  CABIN: "cabin", //e589
  CABLE: "cable", //efe6
  CACHED: "cached", //e86a
  CAKE: "cake", //e7e9
  CALCULATE: "calculate", //ea5f
  CALENDAR_MONTH: "calendar_month", //ebcc
  CALENDAR_TODAY: "calendar_today", //e935
  CALENDAR_VIEW_DAY: "calendar_view_day", //e936
  CALENDAR_VIEW_MONTH: "calendar_view_month", //efe7
  CALENDAR_VIEW_WEEK: "calendar_view_week", //efe8
  CALL: "call", //e0b0
  CALL_END: "call_end", //e0b1
  CALL_MADE: "call_made", //e0b2
  CALL_MERGE: "call_merge", //e0b3
  CALL_MISSED: "call_missed", //e0b4
  CALL_MISSED_OUTGOING: "call_missed_outgoing", //e0e4
  CALL_RECEIVED: "call_received", //e0b5
  CALL_SPLIT: "call_split", //e0b6
  CALL_TO_ACTION: "call_to_action", //e06c
  CAMERA: "camera", //e3af
  CAMERA_ALT: "camera_alt", //e3b0
  CAMERA_ENHANCE: "camera_enhance", //e8fc
  CAMERA_FRONT: "camera_front", //e3b1
  CAMERA_INDOOR: "camera_indoor", //efe9
  CAMERA_OUTDOOR: "camera_outdoor", //efea
  CAMERA_REAR: "camera_rear", //e3b2
  CAMERA_ROLL: "camera_roll", //e3b3
  CAMERASWITCH: "cameraswitch", //efeb
  CAMPAIGN: "campaign", //ef49
  CANCEL: "cancel", //e5c9
  CANCEL_PRESENTATION: "cancel_presentation", //e0e9
  CANCEL_SCHEDULE_SEND: "cancel_schedule_send", //ea39
  CANDLESTICK_CHART: "candlestick_chart", //ead4
  CAR_CRASH: "car_crash", //ebf2
  CAR_RENTAL: "car_rental", //ea55
  CAR_REPAIR: "car_repair", //ea56
  CARD_GIFTCARD: "card_giftcard", //e8f6
  CARD_MEMBERSHIP: "card_membership", //e8f7
  CARD_TRAVEL: "card_travel", //e8f8
  CARPENTER: "carpenter", //f1f8
  CASES: "cases", //e992
  CASINO: "casino", //eb40
  CAST: "cast", //e307
  CAST_CONNECTED: "cast_connected", //e308
  CAST_FOR_EDUCATION: "cast_for_education", //efec
  CASTLE: "castle", //eab1
  CATCHING_POKEMON: "catching_pokemon", //e508
  CATEGORY: "category", //e574
  CELEBRATION: "celebration", //ea65
  CELL_TOWER: "cell_tower", //ebba
  CELL_WIFI: "cell_wifi", //e0ec
  CENTER_FOCUS_STRONG: "center_focus_strong", //e3b4
  CENTER_FOCUS_WEAK: "center_focus_weak", //e3b5
  CHAIR: "chair", //efed
  CHAIR_ALT: "chair_alt", //efee
  CHALET: "chalet", //e585
  CHANGE_CIRCLE: "change_circle", //e2e7
  CHANGE_HISTORY: "change_history", //e86b
  CHARGING_STATION: "charging_station", //f19d
  CHAT: "chat", //e0b7
  CHAT_BUBBLE: "chat_bubble", //e0ca
  CHAT_BUBBLE_OUTLINE: "chat_bubble_outline", //e0cb
  CHECK: "check", //e5ca
  CHECK_BOX: "check_box", //e834
  CHECK_BOX_OUTLINE_BLANK: "check_box_outline_blank", //e835
  CHECK_CIRCLE: "check_circle", //e86c
  CHECK_CIRCLE_OUTLINE: "check_circle_outline", //e92d
  CHECKLIST: "checklist", //e6b1
  CHECKLIST_RTL: "checklist_rtl", //e6b3
  CHECKROOM: "checkroom", //f19e
  CHEVRON_LEFT: "chevron_left", //e5cb
  CHEVRON_RIGHT: "chevron_right", //e5cc
  CHILD_CARE: "child_care", //eb41
  CHILD_FRIENDLY: "child_friendly", //eb42
  CHROME_READER_MODE: "chrome_reader_mode", //e86d
  CHURCH: "church", //eaae
  CIRCLE: "circle", //ef4a
  CIRCLE_NOTIFICATIONS: "circle_notifications", //e994
  CLASS: "class", //e86e
  CLEAN_HANDS: "clean_hands", //f21f
  CLEANING_SERVICES: "cleaning_services", //f0ff
  CLEAR: "clear", //e14c
  CLEAR_ALL: "clear_all", //e0b8
  CLOSE: "close", //e5cd
  CLOSE_FULLSCREEN: "close_fullscreen", //f1cf
  CLOSED_CAPTION: "closed_caption", //e01c
  CLOSED_CAPTION_DISABLED: "closed_caption_disabled", //f1dc
  CLOSED_CAPTION_OFF: "closed_caption_off", //e996
  CLOUD: "cloud", //e2bd
  CLOUD_CIRCLE: "cloud_circle", //e2be
  CLOUD_DONE: "cloud_done", //e2bf
  CLOUD_DOWNLOAD: "cloud_download", //e2c0
  CLOUD_OFF: "cloud_off", //e2c1
  CLOUD_QUEUE: "cloud_queue", //e2c2
  CLOUD_SYNC: "cloud_sync", //eb5a
  CLOUD_UPLOAD: "cloud_upload", //e2c3
  CO2: "co2", //e7b0
  CO_PRESENT: "co_present", //eaf0
  CODE: "code", //e86f
  CODE_OFF: "code_off", //e4f3
  COFFEE: "coffee", //efef
  COFFEE_MAKER: "coffee_maker", //eff0
  COLLECTIONS: "collections", //e3b6
  COLLECTIONS_BOOKMARK: "collections_bookmark", //e431
  COLOR_LENS: "color_lens", //e3b7
  COLORIZE: "colorize", //e3b8
  COMMENT: "comment", //e0b9
  COMMENT_BANK: "comment_bank", //ea4e
  COMMENTS_DISABLED: "comments_disabled", //e7a2
  COMMIT: "commit", //eaf5
  COMMUTE: "commute", //e940
  COMPARE: "compare", //e3b9
  COMPARE_ARROWS: "compare_arrows", //e915
  COMPASS_CALIBRATION: "compass_calibration", //e57c
  COMPOST: "compost", //e761
  COMPRESS: "compress", //e94d
  COMPUTER: "computer", //e30a
  CONFIRMATION_NUM: "confirmation_num", //e638
  CONFIRMATION_NUMBER: "confirmation_number", //e638
  CONNECT_WITHOUT_CONTACT: "connect_without_contact", //f223
  CONNECTED_TV: "connected_tv", //e998
  CONNECTING_AIRPORTS: "connecting_airports", //e7c9
  CONSTRUCTION: "construction", //ea3c
  CONTACT_EMERGENCY: "contact_emergency", //f8d1
  CONTACT_MAIL: "contact_mail", //e0d0
  CONTACT_PAGE: "contact_page", //f22e
  CONTACT_PHONE: "contact_phone", //e0cf
  CONTACT_SUPPORT: "contact_support", //e94c
  CONTACTLESS: "contactless", //ea71
  CONTACTS: "contacts", //e0ba
  CONTENT_COPY: "content_copy", //f08a
  CONTENT_CUT: "content_cut", //f08b
  CONTENT_PASTE: "content_paste", //f098
  CONTENT_PASTE_GO: "content_paste_go", //ea8e
  CONTENT_PASTE_OFF: "content_paste_off", //e4f8
  CONTENT_PASTE_SEARCH: "content_paste_search", //ea9b
  CONTRAST: "contrast", //eb37
  CONTROL_CAMERA: "control_camera", //e074
  CONTROL_POINT: "control_point", //e3ba
  CONTROL_POINT_DUPLICATE: "control_point_duplicate", //e3bb
  COOKIE: "cookie", //eaac
  COPY: "copy", //f08a
  COPY_ALL: "copy_all", //e2ec
  COPYRIGHT: "copyright", //e90c
  CORONAVIRUS: "coronavirus", //f221
  CORPORATE_FARE: "corporate_fare", //f1d0
  COTTAGE: "cottage", //e587
  COUNTERTOPS: "countertops", //f1f7
  CREATE: "create", //e150
  CREATE_NEW_FOLDER: "create_new_folder", //e2cc
  CREDIT_CARD: "credit_card", //e870
  CREDIT_CARD_OFF: "credit_card_off", //e4f4
  CREDIT_SCORE: "credit_score", //eff1
  CRIB: "crib", //e588
  CRISIS_ALERT: "crisis_alert", //ebe9
  CROP: "crop", //e3be
  CROP_16_9: "crop_16_9", //e3bc
  CROP_3_2: "crop_3_2", //e3bd
  CROP_5_4: "crop_5_4", //e3bf
  CROP_7_5: "crop_7_5", //e3c0
  CROP_DIN: "crop_din", //e3c1
  CROP_FREE: "crop_free", //e3c2
  CROP_LANDSCAPE: "crop_landscape", //e3c3
  CROP_ORIGINAL: "crop_original", //e3c4
  CROP_PORTRAIT: "crop_portrait", //e3c5
  CROP_ROTATE: "crop_rotate", //e437
  CROP_SQUARE: "crop_square", //e3c6
  CRUELTY_FREE: "cruelty_free", //e799
  CSS: "css", //eb93
  CURRENCY_BITCOIN: "currency_bitcoin", //ebc5
  CURRENCY_EXCHANGE: "currency_exchange", //eb70
  CURRENCY_FRANC: "currency_franc", //eafa
  CURRENCY_LIRA: "currency_lira", //eaef
  CURRENCY_POUND: "currency_pound", //eaf1
  CURRENCY_RUBLE: "currency_ruble", //eaec
  CURRENCY_RUPEE: "currency_rupee", //eaf7
  CURRENCY_YEN: "currency_yen", //eafb
  CURRENCY_YUAN: "currency_yuan", //eaf9
  CURTAINS: "curtains", //ec1e
  CURTAINS_CLOSED: "curtains_closed", //ec1d
  CUT: "cut", //f08b
  CYCLONE: "cyclone", //ebd5
  DANGEROUS: "dangerous", //e99a
  DARK_MODE: "dark_mode", //e51c
  DASHBOARD: "dashboard", //e871
  DASHBOARD_CUSTOMIZE: "dashboard_customize", //e99b
  DATA_ARRAY: "data_array", //ead1
  DATA_EXPLORATION: "data_exploration", //e76f
  DATA_OBJECT: "data_object", //ead3
  DATA_SAVER_OFF: "data_saver_off", //eff2
  DATA_SAVER_ON: "data_saver_on", //eff3
  DATA_THRESHOLDING: "data_thresholding", //eb9f
  DATA_USAGE: "data_usage", //e1af
  DATASET: "dataset", //f8ee
  DATASET_LINKED: "dataset_linked", //f8ef
  DATE_RANGE: "date_range", //e916
  DEBLUR: "deblur", //eb77
  DECK: "deck", //ea42
  DEHAZE: "dehaze", //e3c7
  DELETE: "delete", //e872
  DELETE_FOREVER: "delete_forever", //e92b
  DELETE_OUTLINE: "delete_outline", //e92e
  DELETE_SWEEP: "delete_sweep", //e16c
  DELIVERY_DINING: "delivery_dining", //ea72
  DENSITY_LARGE: "density_large", //eba9
  DENSITY_MEDIUM: "density_medium", //eb9e
  DENSITY_SMALL: "density_small", //eba8
  DEPARTURE_BOARD: "departure_board", //e576
  DESCRIPTION: "description", //e873
  DESELECT: "deselect", //ebb6
  DESIGN_SERVICES: "design_services", //f10a
  DESK: "desk", //f8f4
  DESKTOP_ACCESS_DISABLED: "desktop_access_disabled", //e99d
  DESKTOP_MAC: "desktop_mac", //e30b
  DESKTOP_WINDOWS: "desktop_windows", //e30c
  DETAILS: "details", //e3c8
  DEVELOPER_BOARD: "developer_board", //e30d
  DEVELOPER_BOARD_OFF: "developer_board_off", //e4ff
  DEVELOPER_MODE: "developer_mode", //e1b0
  DEVICE_HUB: "device_hub", //e335
  DEVICE_THERMOSTAT: "device_thermostat", //e1ff
  DEVICE_UNKNOWN: "device_unknown", //e339
  DEVICES: "devices", //e1b1
  DEVICES_FOLD: "devices_fold", //ebde
  DEVICES_OTHER: "devices_other", //e337
  DIALER_SIP: "dialer_sip", //e0bb
  DIALPAD: "dialpad", //e0bc
  DIAMOND: "diamond", //ead5
  DIFFERENCE: "difference", //eb7d
  DINING: "dining", //eff4
  DINNER_DINING: "dinner_dining", //ea57
  DIRECTIONS: "directions", //e52e
  DIRECTIONS_BIKE: "directions_bike", //e52f
  DIRECTIONS_BOAT: "directions_boat", //e532
  DIRECTIONS_BOAT_FILLED: "directions_boat_filled", //eff5
  DIRECTIONS_BUS: "directions_bus", //e530
  DIRECTIONS_BUS_FILLED: "directions_bus_filled", //eff6
  DIRECTIONS_CAR: "directions_car", //e531
  DIRECTIONS_CAR_FILLED: "directions_car_filled", //eff7
  DIRECTIONS_FERRY: "directions_ferry", //e532
  DIRECTIONS_OFF: "directions_off", //f10f
  DIRECTIONS_RAILWAY: "directions_railway", //e534
  DIRECTIONS_RAILWAY_FILLED: "directions_railway_filled", //eff8
  DIRECTIONS_RUN: "directions_run", //e566
  DIRECTIONS_SUBWAY: "directions_subway", //e533
  DIRECTIONS_SUBWAY_FILLED: "directions_subway_filled", //eff9
  DIRECTIONS_TRAIN: "directions_train", //e534
  DIRECTIONS_TRANSIT: "directions_transit", //e535
  DIRECTIONS_TRANSIT_FILLED: "directions_transit_filled", //effa
  DIRECTIONS_WALK: "directions_walk", //e536
  DIRTY_LENS: "dirty_lens", //ef4b
  DISABLED_BY_DEFAULT: "disabled_by_default", //f230
  DISABLED_VISIBLE: "disabled_visible", //e76e
  DISC_FULL: "disc_full", //e610
  DISCORD: "discord", //ea6c
  DISCOUNT: "discount", //ebc9
  DISPLAY_SETTINGS: "display_settings", //eb97
  DIVERSITY_1: "diversity_1", //f8d7
  DIVERSITY_2: "diversity_2", //f8d8
  DIVERSITY_3: "diversity_3", //f8d9
  DND_FORWARDSLASH: "dnd_forwardslash", //e611
  DNS: "dns", //e875
  DO_DISTURB: "do_disturb", //f08c
  DO_DISTURB_ALT: "do_disturb_alt", //f08d
  DO_DISTURB_OFF: "do_disturb_off", //f08e
  DO_DISTURB_ON: "do_disturb_on", //f08f
  DO_NOT_DISTURB: "do_not_disturb", //e612
  DO_NOT_DISTURB_ALT: "do_not_disturb_alt", //e611
  DO_NOT_DISTURB_OFF: "do_not_disturb_off", //e643
  DO_NOT_DISTURB_ON: "do_not_disturb_on", //e644
  DO_NOT_DISTURB_ON_TOTAL_SILENCE: "do_not_disturb_on_total_silence", //effb
  DO_NOT_STEP: "do_not_step", //f19f
  DO_NOT_TOUCH: "do_not_touch", //f1b0
  DOCK: "dock", //e30e
  DOCUMENT_SCANNER: "document_scanner", //e5fa
  DOMAIN: "domain", //e7ee
  DOMAIN_ADD: "domain_add", //eb62
  DOMAIN_DISABLED: "domain_disabled", //e0ef
  DOMAIN_VERIFICATION: "domain_verification", //ef4c
  DONE: "done", //e876
  DONE_ALL: "done_all", //e877
  DONE_OUTLINE: "done_outline", //e92f
  DONUT_LARGE: "donut_large", //e917
  DONUT_SMALL: "donut_small", //e918
  DOOR_BACK: "door_back", //effc
  DOOR_FRONT: "door_front", //effd
  DOOR_SLIDING: "door_sliding", //effe
  DOORBELL: "doorbell", //efff
  DOUBLE_ARROW: "double_arrow", //ea50
  DOWNHILL_SKIING: "downhill_skiing", //e509
  DOWNLOAD: "download", //f090
  DOWNLOAD_DONE: "download_done", //f091
  DOWNLOAD_FOR_OFFLINE: "download_for_offline", //f000
  DOWNLOADING: "downloading", //f001
  DRAFTS: "drafts", //e151
  DRAG_HANDLE: "drag_handle", //e25d
  DRAG_INDICATOR: "drag_indicator", //e945
  DRAW: "draw", //e746
  DRIVE_ETA: "drive_eta", //e613
  DRIVE_FILE_MOVE: "drive_file_move", //e675
  DRIVE_FILE_MOVE_RTL: "drive_file_move_rtl", //e76d
  DRIVE_FILE_RENAME_OUTLINE: "drive_file_rename_outline", //e9a2
  DRIVE_FOLDER_UPLOAD: "drive_folder_upload", //e9a3
  DRY: "dry", //f1b3
  DRY_CLEANING: "dry_cleaning", //ea58
  DUO: "duo", //e9a5
  DVR: "dvr", //e1b2
  DYNAMIC_FEED: "dynamic_feed", //ea14
  DYNAMIC_FORM: "dynamic_form", //f1bf
  E_MOBILEDATA: "e_mobiledata", //f002
  EARBUDS: "earbuds", //f003
  EARBUDS_BATTERY: "earbuds_battery", //f004
  EAST: "east", //f1df
  ECO: "eco", //ea35
  EDGESENSOR_HIGH: "edgesensor_high", //f005
  EDGESENSOR_LOW: "edgesensor_low", //f006
  EDIT: "edit", //e3c9
  EDIT_ATTRIBUTES: "edit_attributes", //e578
  EDIT_CALENDAR: "edit_calendar", //e742
  EDIT_LOCATION: "edit_location", //e568
  EDIT_LOCATION_ALT: "edit_location_alt", //e1c5
  EDIT_NOTE: "edit_note", //e745
  EDIT_NOTIFICATIONS: "edit_notifications", //e525
  EDIT_OFF: "edit_off", //e950
  EDIT_ROAD: "edit_road", //ef4d
  EGG: "egg", //eacc
  EGG_ALT: "egg_alt", //eac8
  EJECT: "eject", //e8fb
  ELDERLY: "elderly", //f21a
  ELDERLY_WOMAN: "elderly_woman", //eb69
  ELECTRIC_BIKE: "electric_bike", //eb1b
  ELECTRIC_BOLT: "electric_bolt", //ec1c
  ELECTRIC_CAR: "electric_car", //eb1c
  ELECTRIC_METER: "electric_meter", //ec1b
  ELECTRIC_MOPED: "electric_moped", //eb1d
  ELECTRIC_RICKSHAW: "electric_rickshaw", //eb1e
  ELECTRIC_SCOOTER: "electric_scooter", //eb1f
  ELECTRICAL_SERVICES: "electrical_services", //f102
  ELEVATOR: "elevator", //f1a0
  EMAIL: "email", //e0be
  EMERGENCY: "emergency", //e1eb
  EMERGENCY_RECORDING: "emergency_recording", //ebf4
  EMERGENCY_SHARE: "emergency_share", //ebf6
  EMOJI_EMOTIONS: "emoji_emotions", //ea22
  EMOJI_EVENTS: "emoji_events", //ea23
  EMOJI_FLAGS: "emoji_flags", //ea1a
  EMOJI_FOOD_BEVERAGE: "emoji_food_beverage", //ea1b
  EMOJI_NATURE: "emoji_nature", //ea1c
  EMOJI_OBJECTS: "emoji_objects", //ea24
  EMOJI_PEOPLE: "emoji_people", //ea1d
  EMOJI_SYMBOLS: "emoji_symbols", //ea1e
  EMOJI_TRANSPORTATION: "emoji_transportation", //ea1f
  ENERGY_SAVINGS_LEAF: "energy_savings_leaf", //ec1a
  ENGINEERING: "engineering", //ea3d
  ENHANCE_PHOTO_TRANSLATE: "enhance_photo_translate", //e8fc
  ENHANCED_ENCRYPTION: "enhanced_encryption", //e63f
  EQUALIZER: "equalizer", //e01d
  ERROR: "error", //e000
  ERROR_OUTLINE: "error_outline", //e001
  ESCALATOR: "escalator", //f1a1
  ESCALATOR_WARNING: "escalator_warning", //f1ac
  EURO: "euro", //ea15
  EURO_SYMBOL: "euro_symbol", //e926
  EV_STATION: "ev_station", //e56d
  EVENT: "event", //e878
  EVENT_AVAILABLE: "event_available", //e614
  EVENT_BUSY: "event_busy", //e615
  EVENT_NOTE: "event_note", //e616
  EVENT_REPEAT: "event_repeat", //eb7b
  EVENT_SEAT: "event_seat", //e903
  EXIT_TO_APP: "exit_to_app", //e879
  EXPAND: "expand", //e94f
  EXPAND_CIRCLE_DOWN: "expand_circle_down", //e7cd
  EXPAND_LESS: "expand_less", //e5ce
  EXPAND_MORE: "expand_more", //e5cf
  EXPLICIT: "explicit", //e01e
  EXPLORE: "explore", //e87a
  EXPLORE_OFF: "explore_off", //e9a8
  EXPOSURE: "exposure", //e3ca
  EXPOSURE_MINUS_1: "exposure_minus_1", //e3cb
  EXPOSURE_MINUS_2: "exposure_minus_2", //e3cc
  EXPOSURE_NEG_1: "exposure_neg_1", //e3cb
  EXPOSURE_NEG_2: "exposure_neg_2", //e3cc
  EXPOSURE_PLUS_1: "exposure_plus_1", //e3cd
  EXPOSURE_PLUS_2: "exposure_plus_2", //e3ce
  EXPOSURE_ZERO: "exposure_zero", //e3cf
  EXTENSION: "extension", //e87b
  EXTENSION_OFF: "extension_off", //e4f5
  FACE: "face", //e87c
  FACE_2: "face_2", //f8da
  FACE_3: "face_3", //f8db
  FACE_4: "face_4", //f8dc
  FACE_5: "face_5", //f8dd
  FACE_6: "face_6", //f8de
  FACE_RETOUCHING_NATURAL: "face_retouching_natural", //ef4e
  FACE_RETOUCHING_OFF: "face_retouching_off", //f007
  FACE_UNLOCK: "face_unlock", //f008
  FACEBOOK: "facebook", //f234
  FACT_CHECK: "fact_check", //f0c5
  FACTORY: "factory", //ebbc
  FAMILY_RESTROOM: "family_restroom", //f1a2
  FAST_FORWARD: "fast_forward", //e01f
  FAST_REWIND: "fast_rewind", //e020
  FASTFOOD: "fastfood", //e57a
  FAVORITE: "favorite", //e87d
  FAVORITE_BORDER: "favorite_border", //e87e
  FAVORITE_OUTLINE: "favorite_outline", //e87e
  FAX: "fax", //ead8
  FEATURED_PLAY_LIST: "featured_play_list", //e06d
  FEATURED_VIDEO: "featured_video", //e06e
  FEED: "feed", //f009
  FEEDBACK: "feedback", //e87f
  FEMALE: "female", //e590
  FENCE: "fence", //f1f6
  FESTIVAL: "festival", //ea68
  FIBER_DVR: "fiber_dvr", //e05d
  FIBER_MANUAL_RECORD: "fiber_manual_record", //e061
  FIBER_NEW: "fiber_new", //e05e
  FIBER_PIN: "fiber_pin", //e06a
  FIBER_SMART_RECORD: "fiber_smart_record", //e062
  FILE_COPY: "file_copy", //e173
  FILE_DOWNLOAD: "file_download", //e2c4
  FILE_DOWNLOAD_DONE: "file_download_done", //e9aa
  FILE_DOWNLOAD_OFF: "file_download_off", //e4fe
  FILE_OPEN: "file_open", //eaf3
  FILE_PRESENT: "file_present", //ea0e
  FILE_UPLOAD: "file_upload", //e2c6
  FILTER: "filter", //e3d3
  FILTER_1: "filter_1", //e3d0
  FILTER_2: "filter_2", //e3d1
  FILTER_3: "filter_3", //e3d2
  FILTER_4: "filter_4", //e3d4
  FILTER_5: "filter_5", //e3d5
  FILTER_6: "filter_6", //e3d6
  FILTER_7: "filter_7", //e3d7
  FILTER_8: "filter_8", //e3d8
  FILTER_9: "filter_9", //e3d9
  FILTER_9_PLUS: "filter_9_plus", //e3da
  FILTER_ALT: "filter_alt", //ef4f
  FILTER_ALT_OFF: "filter_alt_off", //eb32
  FILTER_B_AND_W: "filter_b_and_w", //e3db
  FILTER_CENTER_FOCUS: "filter_center_focus", //e3dc
  FILTER_DRAMA: "filter_drama", //e3dd
  FILTER_FRAMES: "filter_frames", //e3de
  FILTER_HDR: "filter_hdr", //e3df
  FILTER_LIST: "filter_list", //e152
  FILTER_LIST_OFF: "filter_list_off", //eb57
  FILTER_NONE: "filter_none", //e3e0
  FILTER_TILT_SHIFT: "filter_tilt_shift", //e3e2
  FILTER_VINTAGE: "filter_vintage", //e3e3
  FIND_IN_PAGE: "find_in_page", //e880
  FIND_REPLACE: "find_replace", //e881
  FINGERPRINT: "fingerprint", //e90d
  FIRE_EXTINGUISHER: "fire_extinguisher", //f1d8
  FIRE_HYDRANT_ALT: "fire_hydrant_alt", //f8f1
  FIRE_TRUCK: "fire_truck", //f8f2
  FIREPLACE: "fireplace", //ea43
  FIRST_PAGE: "first_page", //e5dc
  FIT_SCREEN: "fit_screen", //ea10
  FITBIT: "fitbit", //e82b
  FITNESS_CENTER: "fitness_center", //eb43
  FLAG: "flag", //e153
  FLAG_CIRCLE: "flag_circle", //eaf8
  FLAKY: "flaky", //ef50
  FLARE: "flare", //e3e4
  FLASH_AUTO: "flash_auto", //e3e5
  FLASH_OFF: "flash_off", //e3e6
  FLASH_ON: "flash_on", //e3e7
  FLASHLIGHT_OFF: "flashlight_off", //f00a
  FLASHLIGHT_ON: "flashlight_on", //f00b
  FLATWARE: "flatware", //f00c
  FLIGHT: "flight", //e539
  FLIGHT_CLASS: "flight_class", //e7cb
  FLIGHT_LAND: "flight_land", //e904
  FLIGHT_TAKEOFF: "flight_takeoff", //e905
  FLIP: "flip", //e3e8
  FLIP_CAMERA_ANDROID: "flip_camera_android", //ea37
  FLIP_CAMERA_IOS: "flip_camera_ios", //ea38
  FLIP_TO_BACK: "flip_to_back", //e882
  FLIP_TO_FRONT: "flip_to_front", //e883
  FLOOD: "flood", //ebe6
  FLOURESCENT: "flourescent", //f00d
  FLUORESCENT: "fluorescent", //f00d
  FLUTTER_DASH: "flutter_dash", //e00b
  FMD_BAD: "fmd_bad", //f00e
  FMD_GOOD: "fmd_good", //f00f
  FOLDER: "folder", //e2c7
  FOLDER_COPY: "folder_copy", //ebbd
  FOLDER_DELETE: "folder_delete", //eb34
  FOLDER_OFF: "folder_off", //eb83
  FOLDER_OPEN: "folder_open", //e2c8
  FOLDER_SHARED: "folder_shared", //e2c9
  FOLDER_SPECIAL: "folder_special", //e617
  FOLDER_ZIP: "folder_zip", //eb2c
  FOLLOW_THE_SIGNS: "follow_the_signs", //f222
  FONT_DOWNLOAD: "font_download", //e167
  FONT_DOWNLOAD_OFF: "font_download_off", //e4f9
  FOOD_BANK: "food_bank", //f1f2
  FOREST: "forest", //ea99
  FORK_LEFT: "fork_left", //eba0
  FORK_RIGHT: "fork_right", //ebac
  FORMAT_ALIGN_CENTER: "format_align_center", //e234
  FORMAT_ALIGN_JUSTIFY: "format_align_justify", //e235
  FORMAT_ALIGN_LEFT: "format_align_left", //e236
  FORMAT_ALIGN_RIGHT: "format_align_right", //e237
  FORMAT_BOLD: "format_bold", //e238
  FORMAT_CLEAR: "format_clear", //e239
  FORMAT_COLOR_FILL: "format_color_fill", //e23a
  FORMAT_COLOR_RESET: "format_color_reset", //e23b
  FORMAT_COLOR_TEXT: "format_color_text", //e23c
  FORMAT_INDENT_DECREASE: "format_indent_decrease", //e23d
  FORMAT_INDENT_INCREASE: "format_indent_increase", //e23e
  FORMAT_ITALIC: "format_italic", //e23f
  FORMAT_LINE_SPACING: "format_line_spacing", //e240
  FORMAT_LIST_BULLETED: "format_list_bulleted", //e241
  FORMAT_LIST_NUMBERED: "format_list_numbered", //e242
  FORMAT_LIST_NUMBERED_RTL: "format_list_numbered_rtl", //e267
  FORMAT_OVERLINE: "format_overline", //eb65
  FORMAT_PAINT: "format_paint", //e243
  FORMAT_QUOTE: "format_quote", //e244
  FORMAT_SHAPES: "format_shapes", //e25e
  FORMAT_SIZE: "format_size", //e245
  FORMAT_STRIKETHROUGH: "format_strikethrough", //e246
  FORMAT_TEXTDIRECTION_L_TO_R: "format_textdirection_l_to_r", //e247
  FORMAT_TEXTDIRECTION_R_TO_L: "format_textdirection_r_to_l", //e248
  FORMAT_UNDERLINE: "format_underline", //e765
  FORMAT_UNDERLINED: "format_underlined", //e765
  FORT: "fort", //eaad
  FORUM: "forum", //e0bf
  FORWARD: "forward", //e154
  FORWARD_10: "forward_10", //e056
  FORWARD_30: "forward_30", //e057
  FORWARD_5: "forward_5", //e058
  FORWARD_TO_INBOX: "forward_to_inbox", //f187
  FOUNDATION: "foundation", //f200
  FREE_BREAKFAST: "free_breakfast", //eb44
  FREE_CANCELLATION: "free_cancellation", //e748
  FRONT_HAND: "front_hand", //e769
  FULLSCREEN: "fullscreen", //e5d0
  FULLSCREEN_EXIT: "fullscreen_exit", //e5d1
  FUNCTIONS: "functions", //e24a
  G_MOBILEDATA: "g_mobiledata", //f010
  G_TRANSLATE: "g_translate", //e927
  GAMEPAD: "gamepad", //e30f
  GAMES: "games", //e021
  GARAGE: "garage", //f011
  GAS_METER: "gas_meter", //ec19
  GAVEL: "gavel", //e90e
  GENERATING_TOKENS: "generating_tokens", //e749
  GESTURE: "gesture", //e155
  GET_APP: "get_app", //e884
  GIF: "gif", //e908
  GIF_BOX: "gif_box", //e7a3
  GIRL: "girl", //eb68
  GITE: "gite", //e58b
  GOLF_COURSE: "golf_course", //eb45
  GPP_BAD: "gpp_bad", //f012
  GPP_GOOD: "gpp_good", //f013
  GPP_MAYBE: "gpp_maybe", //f014
  GPS_FIXED: "gps_fixed", //e1b3
  GPS_NOT_FIXED: "gps_not_fixed", //e1b4
  GPS_OFF: "gps_off", //e1b5
  GRADE: "grade", //e885
  GRADIENT: "gradient", //e3e9
  GRADING: "grading", //ea4f
  GRAIN: "grain", //e3ea
  GRAPHIC_EQ: "graphic_eq", //e1b8
  GRASS: "grass", //f205
  GRID_3X3: "grid_3x3", //f015
  GRID_4X4: "grid_4x4", //f016
  GRID_GOLDENRATIO: "grid_goldenratio", //f017
  GRID_OFF: "grid_off", //e3eb
  GRID_ON: "grid_on", //e3ec
  GRID_VIEW: "grid_view", //e9b0
  GROUP: "group", //e7ef
  GROUP_ADD: "group_add", //e7f0
  GROUP_OFF: "group_off", //e747
  GROUP_REMOVE: "group_remove", //e7ad
  GROUP_WORK: "group_work", //e886
  GROUPS: "groups", //f233
  GROUPS_2: "groups_2", //f8df
  GROUPS_3: "groups_3", //f8e0
  H_MOBILEDATA: "h_mobiledata", //f018
  H_PLUS_MOBILEDATA: "h_plus_mobiledata", //f019
  HAIL: "hail", //e9b1
  HANDSHAKE: "handshake", //ebcb
  HANDYMAN: "handyman", //f10b
  HARDWARE: "hardware", //ea59
  HD: "hd", //e052
  HDR_AUTO: "hdr_auto", //f01a
  HDR_AUTO_SELECT: "hdr_auto_select", //f01b
  HDR_ENHANCED_SELECT: "hdr_enhanced_select", //ef51
  HDR_OFF: "hdr_off", //e3ed
  HDR_OFF_SELECT: "hdr_off_select", //f01c
  HDR_ON: "hdr_on", //e3ee
  HDR_ON_SELECT: "hdr_on_select", //f01d
  HDR_PLUS: "hdr_plus", //f01e
  HDR_STRONG: "hdr_strong", //e3f1
  HDR_WEAK: "hdr_weak", //e3f2
  HEADPHONES: "headphones", //f01f
  HEADPHONES_BATTERY: "headphones_battery", //f020
  HEADSET: "headset", //e310
  HEADSET_MIC: "headset_mic", //e311
  HEADSET_OFF: "headset_off", //e33a
  HEALING: "healing", //e3f3
  HEALTH_AND_SAFETY: "health_and_safety", //e1d5
  HEARING: "hearing", //e023
  HEARING_DISABLED: "hearing_disabled", //f104
  HEART_BROKEN: "heart_broken", //eac2
  HEAT_PUMP: "heat_pump", //ec18
  HEIGHT: "height", //ea16
  HELP: "help", //e887
  HELP_CENTER: "help_center", //f1c0
  HELP_OUTLINE: "help_outline", //e8fd
  HEVC: "hevc", //f021
  HEXAGON: "hexagon", //eb39
  HIDE_IMAGE: "hide_image", //f022
  HIDE_SOURCE: "hide_source", //f023
  HIGH_QUALITY: "high_quality", //e024
  HIGHLIGHT: "highlight", //e25f
  HIGHLIGHT_ALT: "highlight_alt", //ef52
  HIGHLIGHT_OFF: "highlight_off", //e888
  HIGHLIGHT_REMOVE: "highlight_remove", //e888
  HIKING: "hiking", //e50a
  HISTORY: "history", //e889
  HISTORY_EDU: "history_edu", //ea3e
  HISTORY_TOGGLE_OFF: "history_toggle_off", //f17d
  HIVE: "hive", //eaa6
  HLS: "hls", //eb8a
  HLS_OFF: "hls_off", //eb8c
  HOLIDAY_VILLAGE: "holiday_village", //e58a
  HOME: "home", //e88a
  HOME_MAX: "home_max", //f024
  HOME_MINI: "home_mini", //f025
  HOME_REPAIR_SERVICE: "home_repair_service", //f100
  HOME_WORK: "home_work", //ea09
  HORIZONTAL_DISTRIBUTE: "horizontal_distribute", //e014
  HORIZONTAL_RULE: "horizontal_rule", //f108
  HORIZONTAL_SPLIT: "horizontal_split", //e947
  HOT_TUB: "hot_tub", //eb46
  HOTEL: "hotel", //e53a
  HOTEL_CLASS: "hotel_class", //e743
  HOURGLASS_BOTTOM: "hourglass_bottom", //ea5c
  HOURGLASS_DISABLED: "hourglass_disabled", //ef53
  HOURGLASS_EMPTY: "hourglass_empty", //e88b
  HOURGLASS_FULL: "hourglass_full", //e88c
  HOURGLASS_TOP: "hourglass_top", //ea5b
  HOUSE: "house", //ea44
  HOUSE_SIDING: "house_siding", //f202
  HOUSEBOAT: "houseboat", //e584
  HOW_TO_REG: "how_to_reg", //e174
  HOW_TO_VOTE: "how_to_vote", //e175
  HTML: "html", //eb7e
  HTTP: "http", //e902
  HTTPS: "https", //e88d
  HUB: "hub", //e9f4
  HVAC: "hvac", //f10e
  ICE_SKATING: "ice_skating", //e50b
  ICECREAM: "icecream", //ea69
  IMAGE: "image", //e3f4
  IMAGE_ASPECT_RATIO: "image_aspect_ratio", //e3f5
  IMAGE_NOT_SUPPORTED: "image_not_supported", //f116
  IMAGE_SEARCH: "image_search", //e43f
  IMAGESEARCH_ROLLER: "imagesearch_roller", //e9b4
  IMPORT_CONTACTS: "import_contacts", //e0e0
  IMPORT_EXPORT: "import_export", //e0c3
  IMPORTANT_DEVICES: "important_devices", //e912
  INBOX: "inbox", //e156
  INCOMPLETE_CIRCLE: "incomplete_circle", //e79b
  INDETERMINATE_CHECK_BOX: "indeterminate_check_box", //e909
  INFO: "info", //e88e
  INPUT: "input", //e890
  INSERT_CHART: "insert_chart", //e24b
  INSERT_CHART_OUTLINED: "insert_chart_outlined", //e26a
  INSERT_COMMENT: "insert_comment", //e24c
  INSERT_DRIVE_FILE: "insert_drive_file", //e24d
  INSERT_EMOTICON: "insert_emoticon", //e24e
  INSERT_INVITATION: "insert_invitation", //e24f
  INSERT_LINK: "insert_link", //e250
  INSERT_PAGE_BREAK: "insert_page_break", //eaca
  INSERT_PHOTO: "insert_photo", //e251
  INSIGHTS: "insights", //f092
  INSTALL_DESKTOP: "install_desktop", //eb71
  INSTALL_MOBILE: "install_mobile", //eb72
  INTEGRATION_INSTRUCTIONS: "integration_instructions", //ef54
  INTERESTS: "interests", //e7c8
  INTERPRETER_MODE: "interpreter_mode", //e83b
  INVENTORY: "inventory", //e179
  INVENTORY_2: "inventory_2", //e1a1
  INVERT_COLORS: "invert_colors", //e891
  INVERT_COLORS_OFF: "invert_colors_off", //e0c4
  INVERT_COLORS_ON: "invert_colors_on", //e891
  IOS_SHARE: "ios_share", //e6b8
  IRON: "iron", //e583
  ISO: "iso", //e3f6
  JAVASCRIPT: "javascript", //eb7c
  JOIN_FULL: "join_full", //eaeb
  JOIN_INNER: "join_inner", //eaf4
  JOIN_LEFT: "join_left", //eaf2
  JOIN_RIGHT: "join_right", //eaea
  KAYAKING: "kayaking", //e50c
  KEBAB_DINING: "kebab_dining", //e842
  KEY: "key", //e73c
  KEY_OFF: "key_off", //eb84
  KEYBOARD: "keyboard", //e312
  KEYBOARD_ALT: "keyboard_alt", //f028
  KEYBOARD_ARROW_DOWN: "keyboard_arrow_down", //e313
  KEYBOARD_ARROW_LEFT: "keyboard_arrow_left", //e314
  KEYBOARD_ARROW_RIGHT: "keyboard_arrow_right", //e315
  KEYBOARD_ARROW_UP: "keyboard_arrow_up", //e316
  KEYBOARD_BACKSPACE: "keyboard_backspace", //e317
  KEYBOARD_CAPSLOCK: "keyboard_capslock", //e318
  KEYBOARD_COMMAND_KEY: "keyboard_command_key", //eae7
  KEYBOARD_CONTROL: "keyboard_control", //eae1
  KEYBOARD_CONTROL_KEY: "keyboard_control_key", //eae6
  KEYBOARD_DOUBLE_ARROW_DOWN: "keyboard_double_arrow_down", //ead0
  KEYBOARD_DOUBLE_ARROW_LEFT: "keyboard_double_arrow_left", //eac3
  KEYBOARD_DOUBLE_ARROW_RIGHT: "keyboard_double_arrow_right", //eac9
  KEYBOARD_DOUBLE_ARROW_UP: "keyboard_double_arrow_up", //eacf
  KEYBOARD_HIDE: "keyboard_hide", //e31a
  KEYBOARD_OPTION_KEY: "keyboard_option_key", //eae8
  KEYBOARD_RETURN: "keyboard_return", //e31b
  KEYBOARD_TAB: "keyboard_tab", //e31c
  KEYBOARD_VOICE: "keyboard_voice", //e31d
  KING_BED: "king_bed", //ea45
  KITCHEN: "kitchen", //eb47
  KITESURFING: "kitesurfing", //e50d
  LABEL: "label", //e892
  LABEL_IMPORTANT: "label_important", //e937
  LABEL_OFF: "label_off", //e9b6
  LAN: "lan", //eb2f
  LANDSCAPE: "landscape", //e3f7
  LANDSLIDE: "landslide", //ebd7
  LANGUAGE: "language", //e894
  LAPTOP: "laptop", //e31e
  LAPTOP_CHROMEBOOK: "laptop_chromebook", //e31f
  LAPTOP_MAC: "laptop_mac", //e320
  LAPTOP_WINDOWS: "laptop_windows", //e321
  LAST_PAGE: "last_page", //e5dd
  LAUNCH: "launch", //e895
  LAYERS: "layers", //e53b
  LAYERS_CLEAR: "layers_clear", //e53c
  LEADERBOARD: "leaderboard", //f20c
  LEAK_ADD: "leak_add", //e3f8
  LEAK_REMOVE: "leak_remove", //e3f9
  LEAVE_BAGS_AT_HOME: "leave_bags_at_home", //f23b
  LEGEND_TOGGLE: "legend_toggle", //f11b
  LENS: "lens", //e3fa
  LENS_BLUR: "lens_blur", //f029
  LIBRARY_ADD: "library_add", //e02e
  LIBRARY_ADD_CHECK: "library_add_check", //e9b7
  LIBRARY_BOOKS: "library_books", //e02f
  LIBRARY_MUSIC: "library_music", //e030
  LIGHT: "light", //f02a
  LIGHT_MODE: "light_mode", //e518
  LIGHTBULB: "lightbulb", //e0f0
  LIGHTBULB_CIRCLE: "lightbulb_circle", //ebfe
  LINE_AXIS: "line_axis", //ea9a
  LINE_STYLE: "line_style", //e919
  LINE_WEIGHT: "line_weight", //e91a
  LINEAR_SCALE: "linear_scale", //e260
  LINK: "link", //e157
  LINK_OFF: "link_off", //e16f
  LINKED_CAMERA: "linked_camera", //e438
  LIQUOR: "liquor", //ea60
  LIST: "list", //e896
  LIST_ALT: "list_alt", //e0ee
  LIVE_HELP: "live_help", //e0c6
  LIVE_TV: "live_tv", //e639
  LIVING: "living", //f02b
  LOCAL_ACTIVITY: "local_activity", //e53f
  LOCAL_AIRPORT: "local_airport", //e53d
  LOCAL_ATM: "local_atm", //e53e
  LOCAL_ATTRACTION: "local_attraction", //e53f
  LOCAL_BAR: "local_bar", //e540
  LOCAL_CAFE: "local_cafe", //e541
  LOCAL_CAR_WASH: "local_car_wash", //e542
  LOCAL_CONVENIENCE_STORE: "local_convenience_store", //e543
  LOCAL_DINING: "local_dining", //e556
  LOCAL_DRINK: "local_drink", //e544
  LOCAL_FIRE_DEPARTMENT: "local_fire_department", //ef55
  LOCAL_FLORIST: "local_florist", //e545
  LOCAL_GAS_STATION: "local_gas_station", //e546
  LOCAL_GROCERY_STORE: "local_grocery_store", //e547
  LOCAL_HOSPITAL: "local_hospital", //e548
  LOCAL_HOTEL: "local_hotel", //e549
  LOCAL_LAUNDRY_SERVICE: "local_laundry_service", //e54a
  LOCAL_LIBRARY: "local_library", //e54b
  LOCAL_MALL: "local_mall", //e54c
  LOCAL_MOVIES: "local_movies", //e54d
  LOCAL_OFFER: "local_offer", //e54e
  LOCAL_PARKING: "local_parking", //e54f
  LOCAL_PHARMACY: "local_pharmacy", //e550
  LOCAL_PHONE: "local_phone", //e551
  LOCAL_PIZZA: "local_pizza", //e552
  LOCAL_PLAY: "local_play", //e553
  LOCAL_POLICE: "local_police", //ef56
  LOCAL_POST_OFFICE: "local_post_office", //e554
  LOCAL_PRINT_SHOP: "local_print_shop", //e555
  LOCAL_PRINTSHOP: "local_printshop", //e555
  LOCAL_RESTAURANT: "local_restaurant", //e556
  LOCAL_SEE: "local_see", //e557
  LOCAL_SHIPPING: "local_shipping", //e558
  LOCAL_TAXI: "local_taxi", //e559
  LOCATION_CITY: "location_city", //e7f1
  LOCATION_DISABLED: "location_disabled", //e1b6
  LOCATION_HISTORY: "location_history", //e55a
  LOCATION_OFF: "location_off", //e0c7
  LOCATION_ON: "location_on", //e0c8
  LOCATION_SEARCHING: "location_searching", //e1b7
  LOCK: "lock", //e897
  LOCK_CLOCK: "lock_clock", //ef57
  LOCK_OPEN: "lock_open", //e898
  LOCK_PERSON: "lock_person", //f8f3
  LOCK_RESET: "lock_reset", //eade
  LOGIN: "login", //ea77
  LOGO_DEV: "logo_dev", //ead6
  LOGOUT: "logout", //e9ba
  LOOKS: "looks", //e3fc
  LOOKS_3: "looks_3", //e3fb
  LOOKS_4: "looks_4", //e3fd
  LOOKS_5: "looks_5", //e3fe
  LOOKS_6: "looks_6", //e3ff
  LOOKS_ONE: "looks_one", //e400
  LOOKS_TWO: "looks_two", //e401
  LOOP: "loop", //e028
  LOUPE: "loupe", //e402
  LOW_PRIORITY: "low_priority", //e16d
  LOYALTY: "loyalty", //e89a
  LTE_MOBILEDATA: "lte_mobiledata", //f02c
  LTE_PLUS_MOBILEDATA: "lte_plus_mobiledata", //f02d
  LUGGAGE: "luggage", //f235
  LUNCH_DINING: "lunch_dining", //ea61
  LYRICS: "lyrics", //ec0b
  MACRO_OFF: "macro_off", //f8d2
  MAIL: "mail", //e158
  MAIL_LOCK: "mail_lock", //ec0a
  MAIL_OUTLINE: "mail_outline", //e0e1
  MALE: "male", //e58e
  MAN: "man", //e4eb
  MAN_2: "man_2", //f8e1
  MAN_3: "man_3", //f8e2
  MAN_4: "man_4", //f8e3
  MANAGE_ACCOUNTS: "manage_accounts", //f02e
  MANAGE_HISTORY: "manage_history", //ebe7
  MANAGE_SEARCH: "manage_search", //f02f
  MAP: "map", //e55b
  MAPS_HOME_WORK: "maps_home_work", //f030
  MAPS_UGC: "maps_ugc", //ef58
  MARGIN: "margin", //e9bb
  MARK_AS_UNREAD: "mark_as_unread", //e9bc
  MARK_CHAT_READ: "mark_chat_read", //f18b
  MARK_CHAT_UNREAD: "mark_chat_unread", //f189
  MARK_EMAIL_READ: "mark_email_read", //f18c
  MARK_EMAIL_UNREAD: "mark_email_unread", //f18a
  MARK_UNREAD_CHAT_ALT: "mark_unread_chat_alt", //eb9d
  MARKUNREAD: "markunread", //e159
  MARKUNREAD_MAILBOX: "markunread_mailbox", //e89b
  MASKS: "masks", //f218
  MAXIMIZE: "maximize", //e930
  MEDIA_BLUETOOTH_OFF: "media_bluetooth_off", //f031
  MEDIA_BLUETOOTH_ON: "media_bluetooth_on", //f032
  MEDIATION: "mediation", //efa7
  MEDICAL_INFORMATION: "medical_information", //ebed
  MEDICAL_SERVICES: "medical_services", //f109
  MEDICATION: "medication", //f033
  MEDICATION_LIQUID: "medication_liquid", //ea87
  MEETING_ROOM: "meeting_room", //eb4f
  MEMORY: "memory", //e322
  MENU: "menu", //e5d2
  MENU_BOOK: "menu_book", //ea19
  MENU_OPEN: "menu_open", //e9bd
  MERGE: "merge", //eb98
  MERGE_TYPE: "merge_type", //e252
  MESSAGE: "message", //e0c9
  MESSENGER: "messenger", //e0ca
  MESSENGER_OUTLINE: "messenger_outline", //e0cb
  MIC: "mic", //e029
  MIC_EXTERNAL_OFF: "mic_external_off", //ef59
  MIC_EXTERNAL_ON: "mic_external_on", //ef5a
  MIC_NONE: "mic_none", //e02a
  MIC_OFF: "mic_off", //e02b
  MICROWAVE: "microwave", //f204
  MILITARY_TECH: "military_tech", //ea3f
  MINIMIZE: "minimize", //e931
  MINOR_CRASH: "minor_crash", //ebf1
  MISCELLANEOUS_SERVICES: "miscellaneous_services", //f10c
  MISSED_VIDEO_CALL: "missed_video_call", //e073
  MMS: "mms", //e618
  MOBILE_FRIENDLY: "mobile_friendly", //e200
  MOBILE_OFF: "mobile_off", //e201
  MOBILE_SCREEN_SHARE: "mobile_screen_share", //e0e7
  MOBILEDATA_OFF: "mobiledata_off", //f034
  MODE: "mode", //f097
  MODE_COMMENT: "mode_comment", //e253
  MODE_EDIT: "mode_edit", //e254
  MODE_EDIT_OUTLINE: "mode_edit_outline", //f035
  MODE_FAN_OFF: "mode_fan_off", //ec17
  MODE_NIGHT: "mode_night", //f036
  MODE_OF_TRAVEL: "mode_of_travel", //e7ce
  MODE_STANDBY: "mode_standby", //f037
  MODEL_TRAINING: "model_training", //f0cf
  MONETIZATION_ON: "monetization_on", //e263
  MONEY: "money", //e57d
  MONEY_OFF: "money_off", //e25c
  MONEY_OFF_CSRED: "money_off_csred", //f038
  MONITOR: "monitor", //ef5b
  MONITOR_HEART: "monitor_heart", //eaa2
  MONITOR_WEIGHT: "monitor_weight", //f039
  MONOCHROME_PHOTOS: "monochrome_photos", //e403
  MOOD: "mood", //e7f2
  MOOD_BAD: "mood_bad", //e7f3
  MOPED: "moped", //eb28
  MORE: "more", //e619
  MORE_HORIZ: "more_horiz", //eae1
  MORE_TIME: "more_time", //ea5d
  MORE_VERT: "more_vert", //e5d4
  MOSQUE: "mosque", //eab2
  MOTION_PHOTOS_AUTO: "motion_photos_auto", //f03a
  MOTION_PHOTOS_OFF: "motion_photos_off", //e9c0
  MOTION_PHOTOS_ON: "motion_photos_on", //e9c1
  MOTION_PHOTOS_PAUSE: "motion_photos_pause", //f227
  MOTION_PHOTOS_PAUSED: "motion_photos_paused", //e9c2
  MOTORCYCLE: "motorcycle", //e91b
  MOUSE: "mouse", //e323
  MOVE_DOWN: "move_down", //eb61
  MOVE_TO_INBOX: "move_to_inbox", //e168
  MOVE_UP: "move_up", //eb64
  MOVIE: "movie", //e02c
  MOVIE_CREATION: "movie_creation", //e404
  MOVIE_FILTER: "movie_filter", //e43a
  MOVING: "moving", //e501
  MP: "mp", //e9c3
  MULTILINE_CHART: "multiline_chart", //e6df
  MULTIPLE_STOP: "multiple_stop", //f1b9
  MULTITRACK_AUDIO: "multitrack_audio", //e1b8
  MUSEUM: "museum", //ea36
  MUSIC_NOTE: "music_note", //e405
  MUSIC_OFF: "music_off", //e440
  MUSIC_VIDEO: "music_video", //e063
  MY_LIBRARY_ADD: "my_library_add", //e02e
  MY_LIBRARY_BOOKS: "my_library_books", //e02f
  MY_LIBRARY_MUSIC: "my_library_music", //e030
  MY_LOCATION: "my_location", //e55c
  NAT: "nat", //ef5c
  NATURE: "nature", //e406
  NATURE_PEOPLE: "nature_people", //e407
  NAVIGATE_BEFORE: "navigate_before", //e408
  NAVIGATE_NEXT: "navigate_next", //e409
  NAVIGATION: "navigation", //e55d
  NEAR_ME: "near_me", //e569
  NEAR_ME_DISABLED: "near_me_disabled", //f1ef
  NEARBY_ERROR: "nearby_error", //f03b
  NEARBY_OFF: "nearby_off", //f03c
  NEST_CAM_WIRED_STAND: "nest_cam_wired_stand", //ec16
  NETWORK_CELL: "network_cell", //e1b9
  NETWORK_CHECK: "network_check", //e640
  NETWORK_LOCKED: "network_locked", //e61a
  NETWORK_PING: "network_ping", //ebca
  NETWORK_WIFI: "network_wifi", //e1ba
  NETWORK_WIFI_1_BAR: "network_wifi_1_bar", //ebe4
  NETWORK_WIFI_2_BAR: "network_wifi_2_bar", //ebd6
  NETWORK_WIFI_3_BAR: "network_wifi_3_bar", //ebe1
  NEW_LABEL: "new_label", //e609
  NEW_RELEASES: "new_releases", //e031
  NEWSPAPER: "newspaper", //eb81
  NEXT_PLAN: "next_plan", //ef5d
  NEXT_WEEK: "next_week", //e16a
  NFC: "nfc", //e1bb
  NIGHT_SHELTER: "night_shelter", //f1f1
  NIGHTLIFE: "nightlife", //ea62
  NIGHTLIGHT: "nightlight", //f03d
  NIGHTLIGHT_ROUND: "nightlight_round", //ef5e
  NIGHTS_STAY: "nights_stay", //ea46
  NO_ACCOUNTS: "no_accounts", //f03e
  NO_ADULT_CONTENT: "no_adult_content", //f8fe
  NO_BACKPACK: "no_backpack", //f237
  NO_CELL: "no_cell", //f1a4
  NO_CRASH: "no_crash", //ebf0
  NO_DRINKS: "no_drinks", //f1a5
  NO_ENCRYPTION: "no_encryption", //e641
  NO_ENCRYPTION_GMAILERRORRED: "no_encryption_gmailerrorred", //f03f
  NO_FLASH: "no_flash", //f1a6
  NO_FOOD: "no_food", //f1a7
  NO_LUGGAGE: "no_luggage", //f23b
  NO_MEALS: "no_meals", //f1d6
  NO_MEETING_ROOM: "no_meeting_room", //eb4e
  NO_PHOTOGRAPHY: "no_photography", //f1a8
  NO_SIM: "no_sim", //e0cc
  NO_STROLLER: "no_stroller", //f1af
  NO_TRANSFER: "no_transfer", //f1d5
  NOISE_AWARE: "noise_aware", //ebec
  NOISE_CONTROL_OFF: "noise_control_off", //ebf3
  NORDIC_WALKING: "nordic_walking", //e50e
  NORTH: "north", //f1e0
  NORTH_EAST: "north_east", //f1e1
  NORTH_WEST: "north_west", //f1e2
  NOT_ACCESSIBLE: "not_accessible", //f0fe
  NOT_INTERESTED: "not_interested", //e033
  NOT_LISTED_LOCATION: "not_listed_location", //e575
  NOT_STARTED: "not_started", //f0d1
  NOTE: "note", //e06f
  NOTE_ADD: "note_add", //e89c
  NOTE_ALT: "note_alt", //f040
  NOTES: "notes", //e26c
  NOTIFICATION_ADD: "notification_add", //e399
  NOTIFICATION_IMPORTANT: "notification_important", //e004
  NOTIFICATIONS: "notifications", //e7f4
  NOTIFICATIONS_ACTIVE: "notifications_active", //e7f7
  NOTIFICATIONS_NONE: "notifications_none", //e7f5
  NOTIFICATIONS_OFF: "notifications_off", //e7f6
  NOTIFICATIONS_ON: "notifications_on", //e7f7
  NOTIFICATIONS_PAUSED: "notifications_paused", //e7f8
  NOW_WALLPAPER: "now_wallpaper", //e75f
  NOW_WIDGETS: "now_widgets", //e75e
  NUMBERS: "numbers", //eac7
  OFFLINE_BOLT: "offline_bolt", //e932
  OFFLINE_PIN: "offline_pin", //e90a
  OFFLINE_SHARE: "offline_share", //e9c5
  OIL_BARREL: "oil_barrel", //ec15
  ON_DEVICE_TRAINING: "on_device_training", //ebfd
  ONDEMAND_VIDEO: "ondemand_video", //e63a
  ONLINE_PREDICTION: "online_prediction", //f0eb
  OPACITY: "opacity", //e91c
  OPEN_IN_BROWSER: "open_in_browser", //e89d
  OPEN_IN_FULL: "open_in_full", //f1ce
  OPEN_IN_NEW: "open_in_new", //e89e
  OPEN_IN_NEW_OFF: "open_in_new_off", //e4f6
  OPEN_WITH: "open_with", //e89f
  OTHER_HOUSES: "other_houses", //e58c
  OUTBOND: "outbond", //f228
  OUTBOUND: "outbound", //e1ca
  OUTBOX: "outbox", //ef5f
  OUTDOOR_GRILL: "outdoor_grill", //ea47
  OUTLET: "outlet", //f1d4
  OUTLINED_FLAG: "outlined_flag", //e16e
  OUTPUT: "output", //ebbe
  PADDING: "padding", //e9c8
  PAGES: "pages", //e7f9
  PAGEVIEW: "pageview", //e8a0
  PAID: "paid", //f041
  PALETTE: "palette", //e40a
  PAN_TOOL: "pan_tool", //e925
  PAN_TOOL_ALT: "pan_tool_alt", //ebb9
  PANORAMA: "panorama", //e40b
  PANORAMA_FISH_EYE: "panorama_fish_eye", //e40c
  PANORAMA_FISHEYE: "panorama_fisheye", //e40c
  PANORAMA_HORIZONTAL: "panorama_horizontal", //e40d
  PANORAMA_HORIZONTAL_SELECT: "panorama_horizontal_select", //ef60
  PANORAMA_PHOTOSPHERE: "panorama_photosphere", //e9c9
  PANORAMA_PHOTOSPHERE_SELECT: "panorama_photosphere_select", //e9ca
  PANORAMA_VERTICAL: "panorama_vertical", //e40e
  PANORAMA_VERTICAL_SELECT: "panorama_vertical_select", //ef61
  PANORAMA_WIDE_ANGLE: "panorama_wide_angle", //e40f
  PANORAMA_WIDE_ANGLE_SELECT: "panorama_wide_angle_select", //ef62
  PARAGLIDING: "paragliding", //e50f
  PARK: "park", //ea63
  PARTY_MODE: "party_mode", //e7fa
  PASSWORD: "password", //f042
  PASTE: "paste", //f098
  PATTERN: "pattern", //f043
  PAUSE: "pause", //e034
  PAUSE_CIRCLE: "pause_circle", //e1a2
  PAUSE_CIRCLE_FILLED: "pause_circle_filled", //e035
  PAUSE_CIRCLE_OUTLINE: "pause_circle_outline", //e036
  PAUSE_PRESENTATION: "pause_presentation", //e0ea
  PAYMENT: "payment", //e8a1
  PAYMENTS: "payments", //ef63
  PAYPAL: "paypal", //ea8d
  PEDAL_BIKE: "pedal_bike", //eb29
  PENDING: "pending", //ef64
  PENDING_ACTIONS: "pending_actions", //f1bb
  PENTAGON: "pentagon", //eb50
  PEOPLE: "people", //e7fb
  PEOPLE_ALT: "people_alt", //ea21
  PEOPLE_OUTLINE: "people_outline", //e7fc
  PERCENT: "percent", //eb58
  PERM_CAMERA_MIC: "perm_camera_mic", //e8a2
  PERM_CONTACT_CAL: "perm_contact_cal", //e8a3
  PERM_CONTACT_CALENDAR: "perm_contact_calendar", //e8a3
  PERM_DATA_SETTING: "perm_data_setting", //e8a4
  PERM_DEVICE_INFO: "perm_device_info", //e8a5
  PERM_DEVICE_INFORMATION: "perm_device_information", //e8a5
  PERM_IDENTITY: "perm_identity", //e8a6
  PERM_MEDIA: "perm_media", //e8a7
  PERM_PHONE_MSG: "perm_phone_msg", //e8a8
  PERM_SCAN_WIFI: "perm_scan_wifi", //e8a9
  PERSON: "person", //e7fd
  PERSON_2: "person_2", //f8e4
  PERSON_3: "person_3", //f8e5
  PERSON_4: "person_4", //f8e6
  PERSON_ADD: "person_add", //e7fe
  PERSON_ADD_ALT: "person_add_alt", //ea4d
  PERSON_ADD_ALT_1: "person_add_alt_1", //ef65
  PERSON_ADD_DISABLED: "person_add_disabled", //e9cb
  PERSON_OFF: "person_off", //e510
  PERSON_OUTLINE: "person_outline", //e7ff
  PERSON_PIN: "person_pin", //e55a
  PERSON_PIN_CIRCLE: "person_pin_circle", //e56a
  PERSON_REMOVE: "person_remove", //ef66
  PERSON_REMOVE_ALT_1: "person_remove_alt_1", //ef67
  PERSON_SEARCH: "person_search", //f106
  PERSONAL_INJURY: "personal_injury", //e6da
  PERSONAL_VIDEO: "personal_video", //e63b
  PEST_CONTROL: "pest_control", //f0fa
  PEST_CONTROL_RODENT: "pest_control_rodent", //f0fd
  PETS: "pets", //e91d
  PHISHING: "phishing", //ead7
  PHONE: "phone", //e0cd
  PHONE_ANDROID: "phone_android", //e324
  PHONE_BLUETOOTH_SPEAKER: "phone_bluetooth_speaker", //e61b
  PHONE_CALLBACK: "phone_callback", //e649
  PHONE_DISABLED: "phone_disabled", //e9cc
  PHONE_ENABLED: "phone_enabled", //e9cd
  PHONE_FORWARDED: "phone_forwarded", //e61c
  PHONE_IN_TALK: "phone_in_talk", //e61d
  PHONE_IPHONE: "phone_iphone", //e325
  PHONE_LOCKED: "phone_locked", //e61e
  PHONE_MISSED: "phone_missed", //e61f
  PHONE_PAUSED: "phone_paused", //e620
  PHONELINK: "phonelink", //e326
  PHONELINK_ERASE: "phonelink_erase", //e0db
  PHONELINK_LOCK: "phonelink_lock", //e0dc
  PHONELINK_OFF: "phonelink_off", //e327
  PHONELINK_RING: "phonelink_ring", //e0dd
  PHONELINK_SETUP: "phonelink_setup", //e0de
  PHOTO: "photo", //e410
  PHOTO_ALBUM: "photo_album", //e411
  PHOTO_CAMERA: "photo_camera", //e412
  PHOTO_CAMERA_BACK: "photo_camera_back", //ef68
  PHOTO_CAMERA_FRONT: "photo_camera_front", //ef69
  PHOTO_FILTER: "photo_filter", //e43b
  PHOTO_LIBRARY: "photo_library", //e413
  PHOTO_SIZE_SELECT_ACTUAL: "photo_size_select_actual", //e432
  PHOTO_SIZE_SELECT_LARGE: "photo_size_select_large", //e433
  PHOTO_SIZE_SELECT_SMALL: "photo_size_select_small", //e434
  PHP: "php", //eb8f
  PIANO: "piano", //e521
  PIANO_OFF: "piano_off", //e520
  PICTURE_AS_PDF: "picture_as_pdf", //e415
  PICTURE_IN_PICTURE: "picture_in_picture", //e8aa
  PICTURE_IN_PICTURE_ALT: "picture_in_picture_alt", //e911
  PIE_CHART: "pie_chart", //e6c4
  PIE_CHART_OUTLINE: "pie_chart_outline", //f044
  PIN: "pin", //f045
  PIN_DROP: "pin_drop", //e55e
  PIN_END: "pin_end", //e767
  PIN_INVOKE: "pin_invoke", //e763
  PINCH: "pinch", //eb38
  PIVOT_TABLE_CHART: "pivot_table_chart", //e9ce
  PIX: "pix", //eaa3
  PLACE: "place", //e55f
  PLAGIARISM: "plagiarism", //ea5a
  PLAY_ARROW: "play_arrow", //e037
  PLAY_CIRCLE: "play_circle", //e1c4
  PLAY_CIRCLE_FILL: "play_circle_fill", //e038
  PLAY_CIRCLE_FILLED: "play_circle_filled", //e038
  PLAY_CIRCLE_OUTLINE: "play_circle_outline", //e039
  PLAY_DISABLED: "play_disabled", //ef6a
  PLAY_FOR_WORK: "play_for_work", //e906
  PLAY_LESSON: "play_lesson", //f047
  PLAYLIST_ADD: "playlist_add", //e03b
  PLAYLIST_ADD_CHECK: "playlist_add_check", //e065
  PLAYLIST_ADD_CHECK_CIRCLE: "playlist_add_check_circle", //e7e6
  PLAYLIST_ADD_CIRCLE: "playlist_add_circle", //e7e5
  PLAYLIST_PLAY: "playlist_play", //e05f
  PLAYLIST_REMOVE: "playlist_remove", //eb80
  PLUMBING: "plumbing", //f107
  PLUS_ONE: "plus_one", //e800
  PODCASTS: "podcasts", //f048
  POINT_OF_SALE: "point_of_sale", //f17e
  POLICY: "policy", //ea17
  POLL: "poll", //e801
  POLYLINE: "polyline", //ebbb
  POLYMER: "polymer", //e8ab
  POOL: "pool", //eb48
  PORTABLE_WIFI_OFF: "portable_wifi_off", //e0ce
  PORTRAIT: "portrait", //e416
  POST_ADD: "post_add", //ea20
  POWER: "power", //e63c
  POWER_INPUT: "power_input", //e336
  POWER_OFF: "power_off", //e646
  POWER_SETTINGS_NEW: "power_settings_new", //e8ac
  PRECISION_MANUFACTURING: "precision_manufacturing", //f049
  PREGNANT_WOMAN: "pregnant_woman", //e91e
  PRESENT_TO_ALL: "present_to_all", //e0df
  PREVIEW: "preview", //f1c5
  PRICE_CHANGE: "price_change", //f04a
  PRICE_CHECK: "price_check", //f04b
  PRINT: "print", //e8ad
  PRINT_DISABLED: "print_disabled", //e9cf
  PRIORITY_HIGH: "priority_high", //e645
  PRIVACY_TIP: "privacy_tip", //f0dc
  PRIVATE_CONNECTIVITY: "private_connectivity", //e744
  PRODUCTION_QUANTITY_LIMITS: "production_quantity_limits", //e1d1
  PROPANE: "propane", //ec14
  PROPANE_TANK: "propane_tank", //ec13
  PSYCHOLOGY: "psychology", //ea4a
  PSYCHOLOGY_ALT: "psychology_alt", //f8ea
  PUBLIC: "public", //e80b
  PUBLIC_OFF: "public_off", //f1ca
  PUBLISH: "publish", //e255
  PUBLISHED_WITH_CHANGES: "published_with_changes", //f232
  PUNCH_CLOCK: "punch_clock", //eaa8
  PUSH_PIN: "push_pin", //f10d
  QR_CODE: "qr_code", //ef6b
  QR_CODE_2: "qr_code_2", //e00a
  QR_CODE_SCANNER: "qr_code_scanner", //f206
  QUERY_BUILDER: "query_builder", //e8ae
  QUERY_STATS: "query_stats", //e4fc
  QUESTION_ANSWER: "question_answer", //e8af
  QUESTION_MARK: "question_mark", //eb8b
  QUEUE: "queue", //e03c
  QUEUE_MUSIC: "queue_music", //e03d
  QUEUE_PLAY_NEXT: "queue_play_next", //e066
  QUICK_CONTACTS_DIALER: "quick_contacts_dialer", //e0cf
  QUICK_CONTACTS_MAIL: "quick_contacts_mail", //e0d0
  QUICKREPLY: "quickreply", //ef6c
  QUIZ: "quiz", //f04c
  QUORA: "quora", //ea98
  R_MOBILEDATA: "r_mobiledata", //f04d
  RADAR: "radar", //f04e
  RADIO: "radio", //e03e
  RADIO_BUTTON_CHECKED: "radio_button_checked", //e837
  RADIO_BUTTON_OFF: "radio_button_off", //e836
  RADIO_BUTTON_ON: "radio_button_on", //e837
  RADIO_BUTTON_UNCHECKED: "radio_button_unchecked", //e836
  RAILWAY_ALERT: "railway_alert", //e9d1
  RAMEN_DINING: "ramen_dining", //ea64
  RAMP_LEFT: "ramp_left", //eb9c
  RAMP_RIGHT: "ramp_right", //eb96
  RATE_REVIEW: "rate_review", //e560
  RAW_OFF: "raw_off", //f04f
  RAW_ON: "raw_on", //f050
  READ_MORE: "read_more", //ef6d
  REAL_ESTATE_AGENT: "real_estate_agent", //e73a
  RECEIPT: "receipt", //e8b0
  RECEIPT_LONG: "receipt_long", //ef6e
  RECENT_ACTORS: "recent_actors", //e03f
  RECOMMEND: "recommend", //e9d2
  RECORD_VOICE_OVER: "record_voice_over", //e91f
  RECTANGLE: "rectangle", //eb54
  RECYCLING: "recycling", //e760
  REDDIT: "reddit", //eaa0
  REDEEM: "redeem", //e8b1
  REDO: "redo", //e15a
  REDUCE_CAPACITY: "reduce_capacity", //f21c
  REFRESH: "refresh", //e5d5
  REMEMBER_ME: "remember_me", //f051
  REMOVE: "remove", //e15b
  REMOVE_CIRCLE: "remove_circle", //e15c
  REMOVE_CIRCLE_OUTLINE: "remove_circle_outline", //e15d
  REMOVE_DONE: "remove_done", //e9d3
  REMOVE_FROM_QUEUE: "remove_from_queue", //e067
  REMOVE_MODERATOR: "remove_moderator", //e9d4
  REMOVE_RED_EYE: "remove_red_eye", //e417
  REMOVE_ROAD: "remove_road", //ebfc
  REMOVE_SHOPPING_CART: "remove_shopping_cart", //e928
  REORDER: "reorder", //e8fe
  REPARTITION: "repartition", //f8e8
  REPEAT: "repeat", //e040
  REPEAT_ON: "repeat_on", //e9d6
  REPEAT_ONE: "repeat_one", //e041
  REPEAT_ONE_ON: "repeat_one_on", //e9d7
  REPLAY: "replay", //e042
  REPLAY_10: "replay_10", //e059
  REPLAY_30: "replay_30", //e05a
  REPLAY_5: "replay_5", //e05b
  REPLAY_CIRCLE_FILLED: "replay_circle_filled", //e9d8
  REPLY: "reply", //e15e
  REPLY_ALL: "reply_all", //e15f
  REPORT: "report", //e160
  REPORT_GMAILERRORRED: "report_gmailerrorred", //f052
  REPORT_OFF: "report_off", //e170
  REPORT_PROBLEM: "report_problem", //e8b2
  REQUEST_PAGE: "request_page", //f22c
  REQUEST_QUOTE: "request_quote", //f1b6
  RESET_TV: "reset_tv", //e9d9
  RESTART_ALT: "restart_alt", //f053
  RESTAURANT: "restaurant", //e56c
  RESTAURANT_MENU: "restaurant_menu", //e561
  RESTORE: "restore", //e8b3
  RESTORE_FROM_TRASH: "restore_from_trash", //e938
  RESTORE_PAGE: "restore_page", //e929
  REVIEWS: "reviews", //f054
  RICE_BOWL: "rice_bowl", //f1f5
  RING_VOLUME: "ring_volume", //e0d1
  ROCKET: "rocket", //eba5
  ROCKET_LAUNCH: "rocket_launch", //eb9b
  ROLLER_SHADES: "roller_shades", //ec12
  ROLLER_SHADES_CLOSED: "roller_shades_closed", //ec11
  ROLLER_SKATING: "roller_skating", //ebcd
  ROOFING: "roofing", //f201
  ROOM: "room", //e8b4
  ROOM_PREFERENCES: "room_preferences", //f1b8
  ROOM_SERVICE: "room_service", //eb49
  ROTATE_90_DEGREES_CCW: "rotate_90_degrees_ccw", //e418
  ROTATE_90_DEGREES_CW: "rotate_90_degrees_cw", //eaab
  ROTATE_LEFT: "rotate_left", //e419
  ROTATE_RIGHT: "rotate_right", //e41a
  ROUNDABOUT_LEFT: "roundabout_left", //eb99
  ROUNDABOUT_RIGHT: "roundabout_right", //eba3
  ROUNDED_CORNER: "rounded_corner", //e920
  ROUTE: "route", //eacd
  ROUTER: "router", //e328
  ROWING: "rowing", //e921
  RSS_FEED: "rss_feed", //e0e5
  RSVP: "rsvp", //f055
  RTT: "rtt", //e9ad
  RULE: "rule", //f1c2
  RULE_FOLDER: "rule_folder", //f1c9
  RUN_CIRCLE: "run_circle", //ef6f
  RUNNING_WITH_ERRORS: "running_with_errors", //e51d
  RV_HOOKUP: "rv_hookup", //e642
  SAFETY_CHECK: "safety_check", //ebef
  SAFETY_DIVIDER: "safety_divider", //e1cc
  SAILING: "sailing", //e502
  SANITIZER: "sanitizer", //f21d
  SATELLITE: "satellite", //e562
  SATELLITE_ALT: "satellite_alt", //eb3a
  SAVE: "save", //e161
  SAVE_ALT: "save_alt", //e171
  SAVE_AS: "save_as", //eb60
  SAVED_SEARCH: "saved_search", //ea11
  SAVINGS: "savings", //e2eb
  SCALE: "scale", //eb5f
  SCANNER: "scanner", //e329
  SCATTER_PLOT: "scatter_plot", //e268
  SCHEDULE: "schedule", //e8b5
  SCHEDULE_SEND: "schedule_send", //ea0a
  SCHEMA: "schema", //e4fd
  SCHOOL: "school", //e80c
  SCIENCE: "science", //ea4b
  SCORE: "score", //e269
  SCOREBOARD: "scoreboard", //ebd0
  SCREEN_LOCK_LANDSCAPE: "screen_lock_landscape", //e1be
  SCREEN_LOCK_PORTRAIT: "screen_lock_portrait", //e1bf
  SCREEN_LOCK_ROTATION: "screen_lock_rotation", //e1c0
  SCREEN_ROTATION: "screen_rotation", //e1c1
  SCREEN_ROTATION_ALT: "screen_rotation_alt", //ebee
  SCREEN_SEARCH_DESKTOP: "screen_search_desktop", //ef70
  SCREEN_SHARE: "screen_share", //e0e2
  SCREENSHOT: "screenshot", //f056
  SCREENSHOT_MONITOR: "screenshot_monitor", //ec08
  SCUBA_DIVING: "scuba_diving", //ebce
  SD: "sd", //e9dd
  SD_CARD: "sd_card", //e623
  SD_CARD_ALERT: "sd_card_alert", //f057
  SD_STORAGE: "sd_storage", //e1c2
  SEARCH: "search", //e8b6
  SEARCH_OFF: "search_off", //ea76
  SECURITY: "security", //e32a
  SECURITY_UPDATE: "security_update", //f058
  SECURITY_UPDATE_GOOD: "security_update_good", //f059
  SECURITY_UPDATE_WARNING: "security_update_warning", //f05a
  SEGMENT: "segment", //e94b
  SELECT_ALL: "select_all", //e162
  SELF_IMPROVEMENT: "self_improvement", //ea78
  SELL: "sell", //f05b
  SEND: "send", //e163
  SEND_AND_ARCHIVE: "send_and_archive", //ea0c
  SEND_TIME_EXTENSION: "send_time_extension", //eadb
  SEND_TO_MOBILE: "send_to_mobile", //f05c
  SENSOR_DOOR: "sensor_door", //f1b5
  SENSOR_OCCUPIED: "sensor_occupied", //ec10
  SENSOR_WINDOW: "sensor_window", //f1b4
  SENSORS: "sensors", //e51e
  SENSORS_OFF: "sensors_off", //e51f
  SENTIMENT_DISSATISFIED: "sentiment_dissatisfied", //e811
  SENTIMENT_NEUTRAL: "sentiment_neutral", //e812
  SENTIMENT_SATISFIED: "sentiment_satisfied", //e813
  SENTIMENT_SATISFIED_ALT: "sentiment_satisfied_alt", //e0ed
  SENTIMENT_VERY_DISSATISFIED: "sentiment_very_dissatisfied", //e814
  SENTIMENT_VERY_SATISFIED: "sentiment_very_satisfied", //e815
  SET_MEAL: "set_meal", //f1ea
  SETTINGS: "settings", //e8b8
  SETTINGS_ACCESSIBILITY: "settings_accessibility", //f05d
  SETTINGS_APPLICATIONS: "settings_applications", //e8b9
  SETTINGS_BACKUP_RESTORE: "settings_backup_restore", //e8ba
  SETTINGS_BLUETOOTH: "settings_bluetooth", //e8bb
  SETTINGS_BRIGHTNESS: "settings_brightness", //e8bd
  SETTINGS_CELL: "settings_cell", //e8bc
  SETTINGS_DISPLAY: "settings_display", //e8bd
  SETTINGS_ETHERNET: "settings_ethernet", //e8be
  SETTINGS_INPUT_ANTENNA: "settings_input_antenna", //e8bf
  SETTINGS_INPUT_COMPONENT: "settings_input_component", //e8c0
  SETTINGS_INPUT_COMPOSITE: "settings_input_composite", //e8c1
  SETTINGS_INPUT_HDMI: "settings_input_hdmi", //e8c2
  SETTINGS_INPUT_SVIDEO: "settings_input_svideo", //e8c3
  SETTINGS_OVERSCAN: "settings_overscan", //e8c4
  SETTINGS_PHONE: "settings_phone", //e8c5
  SETTINGS_POWER: "settings_power", //e8c6
  SETTINGS_REMOTE: "settings_remote", //e8c7
  SETTINGS_SUGGEST: "settings_suggest", //f05e
  SETTINGS_SYSTEM_DAYDREAM: "settings_system_daydream", //e1c3
  SETTINGS_VOICE: "settings_voice", //e8c8
  SEVERE_COLD: "severe_cold", //ebd3
  SHAPE_LINE: "shape_line", //f8d3
  SHARE: "share", //e80d
  SHARE_ARRIVAL_TIME: "share_arrival_time", //e524
  SHARE_LOCATION: "share_location", //f05f
  SHIELD: "shield", //e9e0
  SHIELD_MOON: "shield_moon", //eaa9
  SHOP: "shop", //e8c9
  SHOP_2: "shop_2", //e19e
  SHOP_TWO: "shop_two", //e8ca
  SHOPIFY: "shopify", //ea9d
  SHOPPING_BAG: "shopping_bag", //f1cc
  SHOPPING_BASKET: "shopping_basket", //e8cb
  SHOPPING_CART: "shopping_cart", //e8cc
  SHOPPING_CART_CHECKOUT: "shopping_cart_checkout", //eb88
  SHORT_TEXT: "short_text", //e261
  SHORTCUT: "shortcut", //f060
  SHOW_CHART: "show_chart", //e6e1
  SHOWER: "shower", //f061
  SHUFFLE: "shuffle", //e043
  SHUFFLE_ON: "shuffle_on", //e9e1
  SHUTTER_SPEED: "shutter_speed", //e43d
  SICK: "sick", //f220
  SIGN_LANGUAGE: "sign_language", //ebe5
  SIGNAL_CELLULAR_0_BAR: "signal_cellular_0_bar", //f0a8
  SIGNAL_CELLULAR_4_BAR: "signal_cellular_4_bar", //e1c8
  SIGNAL_CELLULAR_ALT: "signal_cellular_alt", //e202
  SIGNAL_CELLULAR_ALT_1_BAR: "signal_cellular_alt_1_bar", //ebdf
  SIGNAL_CELLULAR_ALT_2_BAR: "signal_cellular_alt_2_bar", //ebe3
  SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_0_BAR: "signal_cellular_connected_no_internet_0_bar", //f0ac
  SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_4_BAR: "signal_cellular_connected_no_internet_4_bar", //e1cd
  SIGNAL_CELLULAR_NO_SIM: "signal_cellular_no_sim", //e1ce
  SIGNAL_CELLULAR_NODATA: "signal_cellular_nodata", //f062
  SIGNAL_CELLULAR_NULL: "signal_cellular_null", //e1cf
  SIGNAL_CELLULAR_OFF: "signal_cellular_off", //e1d0
  SIGNAL_WIFI_0_BAR: "signal_wifi_0_bar", //f0b0
  SIGNAL_WIFI_4_BAR: "signal_wifi_4_bar", //e1d8
  SIGNAL_WIFI_4_BAR_LOCK: "signal_wifi_4_bar_lock", //e1d9
  SIGNAL_WIFI_BAD: "signal_wifi_bad", //f063
  SIGNAL_WIFI_CONNECTED_NO_INTERNET_4: "signal_wifi_connected_no_internet_4", //f064
  SIGNAL_WIFI_OFF: "signal_wifi_off", //e1da
  SIGNAL_WIFI_STATUSBAR_4_BAR: "signal_wifi_statusbar_4_bar", //f065
  SIGNAL_WIFI_STATUSBAR_CONNECTED_NO_INTERNET_4: "signal_wifi_statusbar_connected_no_internet_4", //f066
  SIGNAL_WIFI_STATUSBAR_NULL: "signal_wifi_statusbar_null", //f067
  SIGNPOST: "signpost", //eb91
  SIM_CARD: "sim_card", //e32b
  SIM_CARD_ALERT: "sim_card_alert", //e624
  SIM_CARD_DOWNLOAD: "sim_card_download", //f068
  SINGLE_BED: "single_bed", //ea48
  SIP: "sip", //f069
  SKATEBOARDING: "skateboarding", //e511
  SKIP_NEXT: "skip_next", //e044
  SKIP_PREVIOUS: "skip_previous", //e045
  SLEDDING: "sledding", //e512
  SLIDESHOW: "slideshow", //e41b
  SLOW_MOTION_VIDEO: "slow_motion_video", //e068
  SMART_BUTTON: "smart_button", //f1c1
  SMART_DISPLAY: "smart_display", //f06a
  SMART_SCREEN: "smart_screen", //f06b
  SMART_TOY: "smart_toy", //f06c
  SMARTPHONE: "smartphone", //e32c
  SMOKE_FREE: "smoke_free", //eb4a
  SMOKING_ROOMS: "smoking_rooms", //eb4b
  SMS: "sms", //e625
  SMS_FAILED: "sms_failed", //e626
  SNAPCHAT: "snapchat", //ea6e
  SNIPPET_FOLDER: "snippet_folder", //f1c7
  SNOOZE: "snooze", //e046
  SNOWBOARDING: "snowboarding", //e513
  SNOWMOBILE: "snowmobile", //e503
  SNOWSHOEING: "snowshoeing", //e514
  SOAP: "soap", //f1b2
  SOCIAL_DISTANCE: "social_distance", //e1cb
  SOLAR_POWER: "solar_power", //ec0f
  SORT: "sort", //e164
  SORT_BY_ALPHA: "sort_by_alpha", //e053
  SOS: "sos", //ebf7
  SOUP_KITCHEN: "soup_kitchen", //e7d3
  SOURCE: "source", //f1c4
  SOUTH: "south", //f1e3
  SOUTH_AMERICA: "south_america", //e7e4
  SOUTH_EAST: "south_east", //f1e4
  SOUTH_WEST: "south_west", //f1e5
  SPA: "spa", //eb4c
  SPACE_BAR: "space_bar", //e256
  SPACE_DASHBOARD: "space_dashboard", //e66b
  SPATIAL_AUDIO: "spatial_audio", //ebeb
  SPATIAL_AUDIO_OFF: "spatial_audio_off", //ebe8
  SPATIAL_TRACKING: "spatial_tracking", //ebea
  SPEAKER: "speaker", //e32d
  SPEAKER_GROUP: "speaker_group", //e32e
  SPEAKER_NOTES: "speaker_notes", //e8cd
  SPEAKER_NOTES_OFF: "speaker_notes_off", //e92a
  SPEAKER_PHONE: "speaker_phone", //e0d2
  SPEED: "speed", //e9e4
  SPELLCHECK: "spellcheck", //e8ce
  SPLITSCREEN: "splitscreen", //f06d
  SPOKE: "spoke", //e9a7
  SPORTS: "sports", //ea30
  SPORTS_BAR: "sports_bar", //f1f3
  SPORTS_BASEBALL: "sports_baseball", //ea51
  SPORTS_BASKETBALL: "sports_basketball", //ea26
  SPORTS_CRICKET: "sports_cricket", //ea27
  SPORTS_ESPORTS: "sports_esports", //ea28
  SPORTS_FOOTBALL: "sports_football", //ea29
  SPORTS_GOLF: "sports_golf", //ea2a
  SPORTS_GYMNASTICS: "sports_gymnastics", //ebc4
  SPORTS_HANDBALL: "sports_handball", //ea33
  SPORTS_HOCKEY: "sports_hockey", //ea2b
  SPORTS_KABADDI: "sports_kabaddi", //ea34
  SPORTS_MARTIAL_ARTS: "sports_martial_arts", //eae9
  SPORTS_MMA: "sports_mma", //ea2c
  SPORTS_MOTORSPORTS: "sports_motorsports", //ea2d
  SPORTS_RUGBY: "sports_rugby", //ea2e
  SPORTS_SCORE: "sports_score", //f06e
  SPORTS_SOCCER: "sports_soccer", //ea2f
  SPORTS_TENNIS: "sports_tennis", //ea32
  SPORTS_VOLLEYBALL: "sports_volleyball", //ea31
  SQUARE: "square", //eb36
  SQUARE_FOOT: "square_foot", //ea49
  SSID_CHART: "ssid_chart", //eb66
  STACKED_BAR_CHART: "stacked_bar_chart", //e9e6
  STACKED_LINE_CHART: "stacked_line_chart", //f22b
  STADIUM: "stadium", //eb90
  STAIRS: "stairs", //f1a9
  STAR: "star", //e838
  STAR_BORDER: "star_border", //e83a
  STAR_BORDER_PURPLE500: "star_border_purple500", //f099
  STAR_HALF: "star_half", //e839
  STAR_OUTLINE: "star_outline", //f06f
  STAR_PURPLE500: "star_purple500", //f09a
  STAR_RATE: "star_rate", //f0ec
  STARS: "stars", //e8d0
  START: "start", //e089
  STAY_CURRENT_LANDSCAPE: "stay_current_landscape", //e0d3
  STAY_CURRENT_PORTRAIT: "stay_current_portrait", //e0d4
  STAY_PRIMARY_LANDSCAPE: "stay_primary_landscape", //e0d5
  STAY_PRIMARY_PORTRAIT: "stay_primary_portrait", //e0d6
  STICKY_NOTE_2: "sticky_note_2", //f1fc
  STOP: "stop", //e047
  STOP_CIRCLE: "stop_circle", //ef71
  STOP_SCREEN_SHARE: "stop_screen_share", //e0e3
  STORAGE: "storage", //e1db
  STORE: "store", //e8d1
  STORE_MALL_DIRECTORY: "store_mall_directory", //e563
  STOREFRONT: "storefront", //ea12
  STORM: "storm", //f070
  STRAIGHT: "straight", //eb95
  STRAIGHTEN: "straighten", //e41c
  STREAM: "stream", //e9e9
  STREETVIEW: "streetview", //e56e
  STRIKETHROUGH_S: "strikethrough_s", //e257
  STROLLER: "stroller", //f1ae
  STYLE: "style", //e41d
  SUBDIRECTORY_ARROW_LEFT: "subdirectory_arrow_left", //e5d9
  SUBDIRECTORY_ARROW_RIGHT: "subdirectory_arrow_right", //e5da
  SUBJECT: "subject", //e8d2
  SUBSCRIPT: "subscript", //f111
  SUBSCRIPTIONS: "subscriptions", //e064
  SUBTITLES: "subtitles", //e048
  SUBTITLES_OFF: "subtitles_off", //ef72
  SUBWAY: "subway", //e56f
  SUMMARIZE: "summarize", //f071
  SUPERSCRIPT: "superscript", //f112
  SUPERVISED_USER_CIRCLE: "supervised_user_circle", //e939
  SUPERVISOR_ACCOUNT: "supervisor_account", //e8d3
  SUPPORT: "support", //ef73
  SUPPORT_AGENT: "support_agent", //f0e2
  SURFING: "surfing", //e515
  SURROUND_SOUND: "surround_sound", //e049
  SWAP_CALLS: "swap_calls", //e0d7
  SWAP_HORIZ: "swap_horiz", //e8d4
  SWAP_HORIZONTAL_CIRCLE: "swap_horizontal_circle", //e933
  SWAP_VERT: "swap_vert", //e8d5
  SWAP_VERT_CIRCLE: "swap_vert_circle", //e8d6
  SWAP_VERTICAL_CIRCLE: "swap_vertical_circle", //e8d6
  SWIPE: "swipe", //e9ec
  SWIPE_DOWN: "swipe_down", //eb53
  SWIPE_DOWN_ALT: "swipe_down_alt", //eb30
  SWIPE_LEFT: "swipe_left", //eb59
  SWIPE_LEFT_ALT: "swipe_left_alt", //eb33
  SWIPE_RIGHT: "swipe_right", //eb52
  SWIPE_RIGHT_ALT: "swipe_right_alt", //eb56
  SWIPE_UP: "swipe_up", //eb2e
  SWIPE_UP_ALT: "swipe_up_alt", //eb35
  SWIPE_VERTICAL: "swipe_vertical", //eb51
  SWITCH_ACCESS_SHORTCUT: "switch_access_shortcut", //e7e1
  SWITCH_ACCESS_SHORTCUT_ADD: "switch_access_shortcut_add", //e7e2
  SWITCH_ACCOUNT: "switch_account", //e9ed
  SWITCH_CAMERA: "switch_camera", //e41e
  SWITCH_LEFT: "switch_left", //f1d1
  SWITCH_RIGHT: "switch_right", //f1d2
  SWITCH_VIDEO: "switch_video", //e41f
  SYNAGOGUE: "synagogue", //eab0
  SYNC: "sync", //e627
  SYNC_ALT: "sync_alt", //ea18
  SYNC_DISABLED: "sync_disabled", //e628
  SYNC_LOCK: "sync_lock", //eaee
  SYNC_PROBLEM: "sync_problem", //e629
  SYSTEM_SECURITY_UPDATE: "system_security_update", //f072
  SYSTEM_SECURITY_UPDATE_GOOD: "system_security_update_good", //f073
  SYSTEM_SECURITY_UPDATE_WARNING: "system_security_update_warning", //f074
  SYSTEM_UPDATE: "system_update", //e62a
  SYSTEM_UPDATE_ALT: "system_update_alt", //e8d7
  SYSTEM_UPDATE_TV: "system_update_tv", //e8d7
  TAB: "tab", //e8d8
  TAB_UNSELECTED: "tab_unselected", //e8d9
  TABLE_BAR: "table_bar", //ead2
  TABLE_CHART: "table_chart", //e265
  TABLE_RESTAURANT: "table_restaurant", //eac6
  TABLE_ROWS: "table_rows", //f101
  TABLE_VIEW: "table_view", //f1be
  TABLET: "tablet", //e32f
  TABLET_ANDROID: "tablet_android", //e330
  TABLET_MAC: "tablet_mac", //e331
  TAG: "tag", //e9ef
  TAG_FACES: "tag_faces", //e420
  TAKEOUT_DINING: "takeout_dining", //ea74
  TAP_AND_PLAY: "tap_and_play", //e62b
  TAPAS: "tapas", //f1e9
  TASK: "task", //f075
  TASK_ALT: "task_alt", //e2e6
  TAXI_ALERT: "taxi_alert", //ef74
  TELEGRAM: "telegram", //ea6b
  TEMPLE_BUDDHIST: "temple_buddhist", //eab3
  TEMPLE_HINDU: "temple_hindu", //eaaf
  TERMINAL: "terminal", //eb8e
  TERRAIN: "terrain", //e564
  TEXT_DECREASE: "text_decrease", //eadd
  TEXT_FIELDS: "text_fields", //e262
  TEXT_FORMAT: "text_format", //e165
  TEXT_INCREASE: "text_increase", //eae2
  TEXT_ROTATE_UP: "text_rotate_up", //e93a
  TEXT_ROTATE_VERTICAL: "text_rotate_vertical", //e93b
  TEXT_ROTATION_ANGLEDOWN: "text_rotation_angledown", //e93c
  TEXT_ROTATION_ANGLEUP: "text_rotation_angleup", //e93d
  TEXT_ROTATION_DOWN: "text_rotation_down", //e93e
  TEXT_ROTATION_NONE: "text_rotation_none", //e93f
  TEXT_SNIPPET: "text_snippet", //f1c6
  TEXTSMS: "textsms", //e0d8
  TEXTURE: "texture", //e421
  THEATER_COMEDY: "theater_comedy", //ea66
  THEATERS: "theaters", //e8da
  THERMOSTAT: "thermostat", //f076
  THERMOSTAT_AUTO: "thermostat_auto", //f077
  THUMB_DOWN: "thumb_down", //e8db
  THUMB_DOWN_ALT: "thumb_down_alt", //e816
  THUMB_DOWN_OFF_ALT: "thumb_down_off_alt", //e9f2
  THUMB_UP: "thumb_up", //e8dc
  THUMB_UP_ALT: "thumb_up_alt", //e817
  THUMB_UP_OFF_ALT: "thumb_up_off_alt", //e9f3
  THUMBS_UP_DOWN: "thumbs_up_down", //e8dd
  THUNDERSTORM: "thunderstorm", //ebdb
  TIKTOK: "tiktok", //ea7e
  TIME_TO_LEAVE: "time_to_leave", //e62c
  TIMELAPSE: "timelapse", //e422
  TIMELINE: "timeline", //e922
  TIMER: "timer", //e425
  TIMER_10: "timer_10", //e423
  TIMER_10_SELECT: "timer_10_select", //f07a
  TIMER_3: "timer_3", //e424
  TIMER_3_SELECT: "timer_3_select", //f07b
  TIMER_OFF: "timer_off", //e426
  TIPS_AND_UPDATES: "tips_and_updates", //e79a
  TIRE_REPAIR: "tire_repair", //ebc8
  TITLE: "title", //e264
  TOC: "toc", //e8de
  TODAY: "today", //e8df
  TOGGLE_OFF: "toggle_off", //e9f5
  TOGGLE_ON: "toggle_on", //e9f6
  TOKEN: "token", //ea25
  TOLL: "toll", //e8e0
  TONALITY: "tonality", //e427
  TOPIC: "topic", //f1c8
  TORNADO: "tornado", //e199
  TOUCH_APP: "touch_app", //e913
  TOUR: "tour", //ef75
  TOYS: "toys", //e332
  TRACK_CHANGES: "track_changes", //e8e1
  TRAFFIC: "traffic", //e565
  TRAIN: "train", //e570
  TRAM: "tram", //e571
  TRANSCRIBE: "transcribe", //f8ec
  TRANSFER_WITHIN_A_STATION: "transfer_within_a_station", //e572
  TRANSFORM: "transform", //e428
  TRANSGENDER: "transgender", //e58d
  TRANSIT_ENTEREXIT: "transit_enterexit", //e579
  TRANSLATE: "translate", //e8e2
  TRAVEL_EXPLORE: "travel_explore", //e2db
  TRENDING_DOWN: "trending_down", //e8e3
  TRENDING_FLAT: "trending_flat", //e8e4
  TRENDING_NEUTRAL: "trending_neutral", //e8e4
  TRENDING_UP: "trending_up", //e8e5
  TRIP_ORIGIN: "trip_origin", //e57b
  TROUBLESHOOT: "troubleshoot", //e1d2
  TRY: "try", //f07c
  TSUNAMI: "tsunami", //ebd8
  TTY: "tty", //f1aa
  TUNE: "tune", //e429
  TUNGSTEN: "tungsten", //f07d
  TURN_LEFT: "turn_left", //eba6
  TURN_RIGHT: "turn_right", //ebab
  TURN_SHARP_LEFT: "turn_sharp_left", //eba7
  TURN_SHARP_RIGHT: "turn_sharp_right", //ebaa
  TURN_SLIGHT_LEFT: "turn_slight_left", //eba4
  TURN_SLIGHT_RIGHT: "turn_slight_right", //eb9a
  TURNED_IN: "turned_in", //e8e6
  TURNED_IN_NOT: "turned_in_not", //e8e7
  TV: "tv", //e333
  TV_OFF: "tv_off", //e647
  TWO_WHEELER: "two_wheeler", //e9f9
  TYPE_SPECIMEN: "type_specimen", //f8f0
  U_TURN_LEFT: "u_turn_left", //eba1
  U_TURN_RIGHT: "u_turn_right", //eba2
  UMBRELLA: "umbrella", //f1ad
  UNARCHIVE: "unarchive", //e169
  UNDO: "undo", //e166
  UNFOLD_LESS: "unfold_less", //e5d6
  UNFOLD_LESS_DOUBLE: "unfold_less_double", //f8cf
  UNFOLD_MORE: "unfold_more", //e5d7
  UNFOLD_MORE_DOUBLE: "unfold_more_double", //f8d0
  UNPUBLISHED: "unpublished", //f236
  UNSUBSCRIBE: "unsubscribe", //e0eb
  UPCOMING: "upcoming", //f07e
  UPDATE: "update", //e923
  UPDATE_DISABLED: "update_disabled", //e075
  UPGRADE: "upgrade", //f0fb
  UPLOAD: "upload", //f09b
  UPLOAD_FILE: "upload_file", //e9fc
  USB: "usb", //e1e0
  USB_OFF: "usb_off", //e4fa
  VACCINES: "vaccines", //e138
  VAPE_FREE: "vape_free", //ebc6
  VAPING_ROOMS: "vaping_rooms", //ebcf
  VERIFIED: "verified", //ef76
  VERIFIED_USER: "verified_user", //e8e8
  VERTICAL_ALIGN_BOTTOM: "vertical_align_bottom", //e258
  VERTICAL_ALIGN_CENTER: "vertical_align_center", //e259
  VERTICAL_ALIGN_TOP: "vertical_align_top", //e25a
  VERTICAL_DISTRIBUTE: "vertical_distribute", //e076
  VERTICAL_SHADES: "vertical_shades", //ec0e
  VERTICAL_SHADES_CLOSED: "vertical_shades_closed", //ec0d
  VERTICAL_SPLIT: "vertical_split", //e949
  VIBRATION: "vibration", //e62d
  VIDEO_CALL: "video_call", //e070
  VIDEO_CAMERA_BACK: "video_camera_back", //f07f
  VIDEO_CAMERA_FRONT: "video_camera_front", //f080
  VIDEO_CHAT: "video_chat", //f8a0
  VIDEO_COLLECTION: "video_collection", //e04a
  VIDEO_FILE: "video_file", //eb87
  VIDEO_LABEL: "video_label", //e071
  VIDEO_LIBRARY: "video_library", //e04a
  VIDEO_SETTINGS: "video_settings", //ea75
  VIDEO_STABLE: "video_stable", //f081
  VIDEOCAM: "videocam", //e04b
  VIDEOCAM_OFF: "videocam_off", //e04c
  VIDEOGAME_ASSET: "videogame_asset", //e338
  VIDEOGAME_ASSET_OFF: "videogame_asset_off", //e500
  VIEW_AGENDA: "view_agenda", //e8e9
  VIEW_ARRAY: "view_array", //e8ea
  VIEW_CAROUSEL: "view_carousel", //e8eb
  VIEW_COLUMN: "view_column", //e8ec
  VIEW_COMFORTABLE: "view_comfortable", //e42a
  VIEW_COMFY: "view_comfy", //e42a
  VIEW_COMFY_ALT: "view_comfy_alt", //eb73
  VIEW_COMPACT: "view_compact", //e42b
  VIEW_COMPACT_ALT: "view_compact_alt", //eb74
  VIEW_COZY: "view_cozy", //eb75
  VIEW_DAY: "view_day", //e8ed
  VIEW_HEADLINE: "view_headline", //e8ee
  VIEW_IN_AR: "view_in_ar", //e9fe
  VIEW_KANBAN: "view_kanban", //eb7f
  VIEW_LIST: "view_list", //e8ef
  VIEW_MODULE: "view_module", //e8f0
  VIEW_QUILT: "view_quilt", //e8f1
  VIEW_SIDEBAR: "view_sidebar", //f114
  VIEW_STREAM: "view_stream", //e8f2
  VIEW_TIMELINE: "view_timeline", //eb85
  VIEW_WEEK: "view_week", //e8f3
  VIGNETTE: "vignette", //e435
  VILLA: "villa", //e586
  VISIBILITY: "visibility", //e8f4
  VISIBILITY_OFF: "visibility_off", //e8f5
  VOICE_CHAT: "voice_chat", //e62e
  VOICE_OVER_OFF: "voice_over_off", //e94a
  VOICEMAIL: "voicemail", //e0d9
  VOLCANO: "volcano", //ebda
  VOLUME_DOWN: "volume_down", //e04d
  VOLUME_MUTE: "volume_mute", //e04e
  VOLUME_OFF: "volume_off", //e04f
  VOLUME_UP: "volume_up", //e050
  VOLUNTEER_ACTIVISM: "volunteer_activism", //ea70
  VPN_KEY: "vpn_key", //e0da
  VPN_KEY_OFF: "vpn_key_off", //eb7a
  VPN_LOCK: "vpn_lock", //e62f
  VRPANO: "vrpano", //f082
  WALLET: "wallet", //f8ff
  WALLET_GIFTCARD: "wallet_giftcard", //e8f6
  WALLET_MEMBERSHIP: "wallet_membership", //e8f7
  WALLET_TRAVEL: "wallet_travel", //e8f8
  WALLPAPER: "wallpaper", //e75f
  WAREHOUSE: "warehouse", //ebb8
  WARNING: "warning", //e002
  WARNING_AMBER: "warning_amber", //f083
  WASH: "wash", //f1b1
  WATCH: "watch", //e334
  WATCH_LATER: "watch_later", //e924
  WATCH_OFF: "watch_off", //eae3
  WATER: "water", //f084
  WATER_DAMAGE: "water_damage", //f203
  WATER_DROP: "water_drop", //e798
  WATERFALL_CHART: "waterfall_chart", //ea00
  WAVES: "waves", //e176
  WAVING_HAND: "waving_hand", //e766
  WB_AUTO: "wb_auto", //e42c
  WB_CLOUDY: "wb_cloudy", //e42d
  WB_INCANDESCENT: "wb_incandescent", //e42e
  WB_IRIDESCENT: "wb_iridescent", //e436
  WB_SHADE: "wb_shade", //ea01
  WB_SUNNY: "wb_sunny", //e430
  WB_TWILIGHT: "wb_twilight", //e1c6
  WC: "wc", //e63d
  WEB: "web", //e051
  WEB_ASSET: "web_asset", //e069
  WEB_ASSET_OFF: "web_asset_off", //e4f7
  WEB_STORIES: "web_stories", //e595
  WEBHOOK: "webhook", //eb92
  WECHAT: "wechat", //ea81
  WEEKEND: "weekend", //e16b
  WEST: "west", //f1e6
  WHATSHOT: "whatshot", //e80e
  WHEELCHAIR_PICKUP: "wheelchair_pickup", //f1ab
  WHERE_TO_VOTE: "where_to_vote", //e177
  WIDGETS: "widgets", //e75e
  WIDTH_FULL: "width_full", //f8f5
  WIDTH_NORMAL: "width_normal", //f8f6
  WIDTH_WIDE: "width_wide", //f8f7
  WIFI: "wifi", //e63e
  WIFI_1_BAR: "wifi_1_bar", //e4ca
  WIFI_2_BAR: "wifi_2_bar", //e4d9
  WIFI_CALLING: "wifi_calling", //ef77
  WIFI_CALLING_3: "wifi_calling_3", //f085
  WIFI_CHANNEL: "wifi_channel", //eb6a
  WIFI_FIND: "wifi_find", //eb31
  WIFI_LOCK: "wifi_lock", //e1e1
  WIFI_OFF: "wifi_off", //e648
  WIFI_PASSWORD: "wifi_password", //eb6b
  WIFI_PROTECTED_SETUP: "wifi_protected_setup", //f0fc
  WIFI_TETHERING: "wifi_tethering", //e1e2
  WIFI_TETHERING_ERROR: "wifi_tethering_error", //f086
  WIFI_TETHERING_ERROR_ROUNDED: "wifi_tethering_error_rounded", //f086
  WIFI_TETHERING_OFF: "wifi_tethering_off", //f087
  WIND_POWER: "wind_power", //ec0c
  WINDOW: "window", //f088
  WINE_BAR: "wine_bar", //f1e8
  WOMAN: "woman", //e13e
  WOMAN_2: "woman_2", //f8e7
  WOO_COMMERCE: "woo_commerce", //ea6d
  WORDPRESS: "wordpress", //ea9f
  WORK: "work", //e8f9
  WORK_HISTORY: "work_history", //ec09
  WORK_OFF: "work_off", //e942
  WORK_OUTLINE: "work_outline", //e943
  WORKSPACE_PREMIUM: "workspace_premium", //e7af
  WORKSPACES: "workspaces", //e1a0
  WRAP_TEXT: "wrap_text", //e25b
  WRONG_LOCATION: "wrong_location", //ef78
  WYSIWYG: "wysiwyg", //f1c3
  YARD: "yard", //f089
  YOUTUBE_SEARCHED_FOR: "youtube_searched_for", //e8fa
  ZOOM_IN: "zoom_in", //e8ff
  ZOOM_IN_MAP: "zoom_in_map", //eb2d
  ZOOM_OUT: "zoom_out", //e900
  ZOOM_OUT_MAP: "zoom_out_map", //e56b"
};
